//
//Copyright The Kubernetes Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file was autogenerated by go-to-protobuf. Do not edit it manually!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: k8s.io/apimachinery/pkg/util/intstr/generated.proto

package intstr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IntOrString is a type that can hold an int32 or a string.  When used in
// JSON or YAML marshalling and unmarshalling, it produces or consumes the
// inner type.  This allows you to have, for example, a JSON field that can
// accept a name or number.
// TODO: Rename to Int32OrString
//
// +protobuf=true
// +protobuf.options.(gogoproto.goproto_stringer)=false
// +k8s:openapi-gen=true
// +k8s:openapi-model-package=io.k8s.apimachinery.pkg.util.intstr
type IntOrString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *int64                 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	IntVal        *int32                 `protobuf:"varint,2,opt,name=intVal" json:"intVal,omitempty"`
	StrVal        *string                `protobuf:"bytes,3,opt,name=strVal" json:"strVal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntOrString) Reset() {
	*x = IntOrString{}
	mi := &file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntOrString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntOrString) ProtoMessage() {}

func (x *IntOrString) ProtoReflect() protoreflect.Message {
	mi := &file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntOrString.ProtoReflect.Descriptor instead.
func (*IntOrString) Descriptor() ([]byte, []int) {
	return file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDescGZIP(), []int{0}
}

func (x *IntOrString) GetType() int64 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *IntOrString) GetIntVal() int32 {
	if x != nil && x.IntVal != nil {
		return *x.IntVal
	}
	return 0
}

func (x *IntOrString) GetStrVal() string {
	if x != nil && x.StrVal != nil {
		return *x.StrVal
	}
	return ""
}

var File_k8s_io_apimachinery_pkg_util_intstr_generated_proto protoreflect.FileDescriptor

const file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDesc = "" +
	"\n" +
	"3k8s.io/apimachinery/pkg/util/intstr/generated.proto\x12#k8s.io.apimachinery.pkg.util.intstr\"Q\n" +
	"\vIntOrString\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x03R\x04type\x12\x16\n" +
	"\x06intVal\x18\x02 \x01(\x05R\x06intVal\x12\x16\n" +
	"\x06strVal\x18\x03 \x01(\tR\x06strValB]Z[github.com/runtime-radar/runtime-radar/kube-manager/api/k8s.io/apimachinery/pkg/util/intstr"

var (
	file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDescOnce sync.Once
	file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDescData []byte
)

func file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDescGZIP() []byte {
	file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDescOnce.Do(func() {
		file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDesc), len(file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDesc)))
	})
	return file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDescData
}

var file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_goTypes = []any{
	(*IntOrString)(nil), // 0: k8s.io.apimachinery.pkg.util.intstr.IntOrString
}
var file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_init() }
func file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_init() {
	if File_k8s_io_apimachinery_pkg_util_intstr_generated_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDesc), len(file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_goTypes,
		DependencyIndexes: file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_depIdxs,
		MessageInfos:      file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_msgTypes,
	}.Build()
	File_k8s_io_apimachinery_pkg_util_intstr_generated_proto = out.File
	file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_goTypes = nil
	file_k8s_io_apimachinery_pkg_util_intstr_generated_proto_depIdxs = nil
}
