{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.fullname.namespace" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.fullname.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.serviceAccountName" . }}
    namespace: {{ include "common.namespace" . | quote }}
{{- end }}

