{{- if .Values.networkPolicy.enabled }}
{{- $tlsEnabled := eq (include "common.tls.enabled" .) "true" }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - ports:
        - port: {{ .Values.service.ports.http }}
        {{- if $tlsEnabled }}
        - port: {{ .Values.service.ports.https }}
        {{- end }}
        - port: {{ .Values.service.ports.tcp }}
        {{- if $tlsEnabled }}
        - port: {{ .Values.service.ports.tcpSecure }}
        {{- end }}
        {{- if .Values.keeper.enabled }}
        - port: {{ .Values.service.ports.keeper }}
        - port: {{ .Values.service.ports.keeperInter }}
        {{- if $tlsEnabled }}
        - port: {{ .Values.service.ports.keeperSecure }}
        {{- end }}
        {{- end }}
        - port: {{ .Values.service.ports.mysql }}
        - port: {{ .Values.service.ports.postgresql }}
        - port: {{ .Values.service.ports.interserver }}
        {{- if (eq (include "common.metrics.enabled" .) "true") }}
        - port: {{ .Values.service.ports.metrics }}
        {{- end }}
      to:
        - podSelector:
            matchLabels:
              {{- include "common.selectorLabels" . | nindent 14 }}
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ingress:
    - ports:
        - port: {{ .Values.containerPorts.http }}
        - port: {{ .Values.containerPorts.tcp }}
        - port: {{ .Values.containerPorts.mysql }}
        - port: {{ .Values.containerPorts.postgresql }}
        - port: {{ .Values.containerPorts.interserver }}
        {{- if $tlsEnabled }}
        - port: {{ .Values.containerPorts.tcpSecure }}
        - port: {{ .Values.containerPorts.https }}
        {{- end }}
        {{- if .Values.keeper.enabled }}
        - port: {{ .Values.containerPorts.keeper }}
        - port: {{ .Values.containerPorts.keeperInter }}
        {{- if $tlsEnabled }}
        - port : {{ .Values.containerPorts.keeperSecure }}
        {{- end }}
        {{- end }}
        {{- if (eq (include "common.metrics.enabled" $) "true") }}
        - port: {{ .Values.containerPorts.metrics }}
        {{- end }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{- include "common.selectorLabels" . | nindent 14 }}
        - podSelector:
            matchLabels:
              {{ include "common.fullname" . }}-client: "true"
      {{- end }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
