{{- if and (not .Values.auth.existingSecret) (not ((.Values.global.grafana).auth).existingSecret) }}
{{- $secretName := include "common.auth.secretName" . }}
{{- $key := include "grafana.secretPasswordKey" . }}
{{- $password := include "common.secrets.password" (dict "context" . "secret" $secretName "key" $key "defaultValue" .Values.auth.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "common.namespace" . | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ $key }}: {{ $password | b64enc | quote }}
{{- end }}
