// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package client

import (
	context "context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	mm_api "github.com/runtime-radar/runtime-radar/policy-enforcer/api"
	grpc "google.golang.org/grpc"
)

// EnforcerClientMock implements mm_api.EnforcerClient
type EnforcerClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcEvaluatePolicyRuntimeEvent          func(ctx context.Context, in *mm_api.EvaluatePolicyRuntimeEventReq, opts ...grpc.CallOption) (ep1 *mm_api.EvaluatePolicyRuntimeEventReq, err error)
	funcEvaluatePolicyRuntimeEventOrigin    string
	inspectFuncEvaluatePolicyRuntimeEvent   func(ctx context.Context, in *mm_api.EvaluatePolicyRuntimeEventReq, opts ...grpc.CallOption)
	afterEvaluatePolicyRuntimeEventCounter  uint64
	beforeEvaluatePolicyRuntimeEventCounter uint64
	EvaluatePolicyRuntimeEventMock          mEnforcerClientMockEvaluatePolicyRuntimeEvent
}

// NewEnforcerClientMock returns a mock for mm_api.EnforcerClient
func NewEnforcerClientMock(t minimock.Tester) *EnforcerClientMock {
	m := &EnforcerClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.EvaluatePolicyRuntimeEventMock = mEnforcerClientMockEvaluatePolicyRuntimeEvent{mock: m}
	m.EvaluatePolicyRuntimeEventMock.callArgs = []*EnforcerClientMockEvaluatePolicyRuntimeEventParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mEnforcerClientMockEvaluatePolicyRuntimeEvent struct {
	optional           bool
	mock               *EnforcerClientMock
	defaultExpectation *EnforcerClientMockEvaluatePolicyRuntimeEventExpectation
	expectations       []*EnforcerClientMockEvaluatePolicyRuntimeEventExpectation

	callArgs []*EnforcerClientMockEvaluatePolicyRuntimeEventParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// EnforcerClientMockEvaluatePolicyRuntimeEventExpectation specifies expectation struct of the EnforcerClient.EvaluatePolicyRuntimeEvent
type EnforcerClientMockEvaluatePolicyRuntimeEventExpectation struct {
	mock               *EnforcerClientMock
	params             *EnforcerClientMockEvaluatePolicyRuntimeEventParams
	paramPtrs          *EnforcerClientMockEvaluatePolicyRuntimeEventParamPtrs
	expectationOrigins EnforcerClientMockEvaluatePolicyRuntimeEventExpectationOrigins
	results            *EnforcerClientMockEvaluatePolicyRuntimeEventResults
	returnOrigin       string
	Counter            uint64
}

// EnforcerClientMockEvaluatePolicyRuntimeEventParams contains parameters of the EnforcerClient.EvaluatePolicyRuntimeEvent
type EnforcerClientMockEvaluatePolicyRuntimeEventParams struct {
	ctx  context.Context
	in   *mm_api.EvaluatePolicyRuntimeEventReq
	opts []grpc.CallOption
}

// EnforcerClientMockEvaluatePolicyRuntimeEventParamPtrs contains pointers to parameters of the EnforcerClient.EvaluatePolicyRuntimeEvent
type EnforcerClientMockEvaluatePolicyRuntimeEventParamPtrs struct {
	ctx  *context.Context
	in   **mm_api.EvaluatePolicyRuntimeEventReq
	opts *[]grpc.CallOption
}

// EnforcerClientMockEvaluatePolicyRuntimeEventResults contains results of the EnforcerClient.EvaluatePolicyRuntimeEvent
type EnforcerClientMockEvaluatePolicyRuntimeEventResults struct {
	ep1 *mm_api.EvaluatePolicyRuntimeEventReq
	err error
}

// EnforcerClientMockEvaluatePolicyRuntimeEventOrigins contains origins of expectations of the EnforcerClient.EvaluatePolicyRuntimeEvent
type EnforcerClientMockEvaluatePolicyRuntimeEventExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) Optional() *mEnforcerClientMockEvaluatePolicyRuntimeEvent {
	mmEvaluatePolicyRuntimeEvent.optional = true
	return mmEvaluatePolicyRuntimeEvent
}

// Expect sets up expected params for EnforcerClient.EvaluatePolicyRuntimeEvent
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) Expect(ctx context.Context, in *mm_api.EvaluatePolicyRuntimeEventReq, opts ...grpc.CallOption) *mEnforcerClientMockEvaluatePolicyRuntimeEvent {
	if mmEvaluatePolicyRuntimeEvent.mock.funcEvaluatePolicyRuntimeEvent != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("EnforcerClientMock.EvaluatePolicyRuntimeEvent mock is already set by Set")
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation == nil {
		mmEvaluatePolicyRuntimeEvent.defaultExpectation = &EnforcerClientMockEvaluatePolicyRuntimeEventExpectation{}
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation.paramPtrs != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("EnforcerClientMock.EvaluatePolicyRuntimeEvent mock is already set by ExpectParams functions")
	}

	mmEvaluatePolicyRuntimeEvent.defaultExpectation.params = &EnforcerClientMockEvaluatePolicyRuntimeEventParams{ctx, in, opts}
	mmEvaluatePolicyRuntimeEvent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmEvaluatePolicyRuntimeEvent.expectations {
		if minimock.Equal(e.params, mmEvaluatePolicyRuntimeEvent.defaultExpectation.params) {
			mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmEvaluatePolicyRuntimeEvent.defaultExpectation.params)
		}
	}

	return mmEvaluatePolicyRuntimeEvent
}

// ExpectCtxParam1 sets up expected param ctx for EnforcerClient.EvaluatePolicyRuntimeEvent
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) ExpectCtxParam1(ctx context.Context) *mEnforcerClientMockEvaluatePolicyRuntimeEvent {
	if mmEvaluatePolicyRuntimeEvent.mock.funcEvaluatePolicyRuntimeEvent != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("EnforcerClientMock.EvaluatePolicyRuntimeEvent mock is already set by Set")
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation == nil {
		mmEvaluatePolicyRuntimeEvent.defaultExpectation = &EnforcerClientMockEvaluatePolicyRuntimeEventExpectation{}
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation.params != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("EnforcerClientMock.EvaluatePolicyRuntimeEvent mock is already set by Expect")
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation.paramPtrs == nil {
		mmEvaluatePolicyRuntimeEvent.defaultExpectation.paramPtrs = &EnforcerClientMockEvaluatePolicyRuntimeEventParamPtrs{}
	}
	mmEvaluatePolicyRuntimeEvent.defaultExpectation.paramPtrs.ctx = &ctx
	mmEvaluatePolicyRuntimeEvent.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmEvaluatePolicyRuntimeEvent
}

// ExpectInParam2 sets up expected param in for EnforcerClient.EvaluatePolicyRuntimeEvent
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) ExpectInParam2(in *mm_api.EvaluatePolicyRuntimeEventReq) *mEnforcerClientMockEvaluatePolicyRuntimeEvent {
	if mmEvaluatePolicyRuntimeEvent.mock.funcEvaluatePolicyRuntimeEvent != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("EnforcerClientMock.EvaluatePolicyRuntimeEvent mock is already set by Set")
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation == nil {
		mmEvaluatePolicyRuntimeEvent.defaultExpectation = &EnforcerClientMockEvaluatePolicyRuntimeEventExpectation{}
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation.params != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("EnforcerClientMock.EvaluatePolicyRuntimeEvent mock is already set by Expect")
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation.paramPtrs == nil {
		mmEvaluatePolicyRuntimeEvent.defaultExpectation.paramPtrs = &EnforcerClientMockEvaluatePolicyRuntimeEventParamPtrs{}
	}
	mmEvaluatePolicyRuntimeEvent.defaultExpectation.paramPtrs.in = &in
	mmEvaluatePolicyRuntimeEvent.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmEvaluatePolicyRuntimeEvent
}

// ExpectOptsParam3 sets up expected param opts for EnforcerClient.EvaluatePolicyRuntimeEvent
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) ExpectOptsParam3(opts ...grpc.CallOption) *mEnforcerClientMockEvaluatePolicyRuntimeEvent {
	if mmEvaluatePolicyRuntimeEvent.mock.funcEvaluatePolicyRuntimeEvent != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("EnforcerClientMock.EvaluatePolicyRuntimeEvent mock is already set by Set")
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation == nil {
		mmEvaluatePolicyRuntimeEvent.defaultExpectation = &EnforcerClientMockEvaluatePolicyRuntimeEventExpectation{}
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation.params != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("EnforcerClientMock.EvaluatePolicyRuntimeEvent mock is already set by Expect")
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation.paramPtrs == nil {
		mmEvaluatePolicyRuntimeEvent.defaultExpectation.paramPtrs = &EnforcerClientMockEvaluatePolicyRuntimeEventParamPtrs{}
	}
	mmEvaluatePolicyRuntimeEvent.defaultExpectation.paramPtrs.opts = &opts
	mmEvaluatePolicyRuntimeEvent.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmEvaluatePolicyRuntimeEvent
}

// Inspect accepts an inspector function that has same arguments as the EnforcerClient.EvaluatePolicyRuntimeEvent
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) Inspect(f func(ctx context.Context, in *mm_api.EvaluatePolicyRuntimeEventReq, opts ...grpc.CallOption)) *mEnforcerClientMockEvaluatePolicyRuntimeEvent {
	if mmEvaluatePolicyRuntimeEvent.mock.inspectFuncEvaluatePolicyRuntimeEvent != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("Inspect function is already set for EnforcerClientMock.EvaluatePolicyRuntimeEvent")
	}

	mmEvaluatePolicyRuntimeEvent.mock.inspectFuncEvaluatePolicyRuntimeEvent = f

	return mmEvaluatePolicyRuntimeEvent
}

// Return sets up results that will be returned by EnforcerClient.EvaluatePolicyRuntimeEvent
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) Return(ep1 *mm_api.EvaluatePolicyRuntimeEventReq, err error) *EnforcerClientMock {
	if mmEvaluatePolicyRuntimeEvent.mock.funcEvaluatePolicyRuntimeEvent != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("EnforcerClientMock.EvaluatePolicyRuntimeEvent mock is already set by Set")
	}

	if mmEvaluatePolicyRuntimeEvent.defaultExpectation == nil {
		mmEvaluatePolicyRuntimeEvent.defaultExpectation = &EnforcerClientMockEvaluatePolicyRuntimeEventExpectation{mock: mmEvaluatePolicyRuntimeEvent.mock}
	}
	mmEvaluatePolicyRuntimeEvent.defaultExpectation.results = &EnforcerClientMockEvaluatePolicyRuntimeEventResults{ep1, err}
	mmEvaluatePolicyRuntimeEvent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmEvaluatePolicyRuntimeEvent.mock
}

// Set uses given function f to mock the EnforcerClient.EvaluatePolicyRuntimeEvent method
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) Set(f func(ctx context.Context, in *mm_api.EvaluatePolicyRuntimeEventReq, opts ...grpc.CallOption) (ep1 *mm_api.EvaluatePolicyRuntimeEventReq, err error)) *EnforcerClientMock {
	if mmEvaluatePolicyRuntimeEvent.defaultExpectation != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("Default expectation is already set for the EnforcerClient.EvaluatePolicyRuntimeEvent method")
	}

	if len(mmEvaluatePolicyRuntimeEvent.expectations) > 0 {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("Some expectations are already set for the EnforcerClient.EvaluatePolicyRuntimeEvent method")
	}

	mmEvaluatePolicyRuntimeEvent.mock.funcEvaluatePolicyRuntimeEvent = f
	mmEvaluatePolicyRuntimeEvent.mock.funcEvaluatePolicyRuntimeEventOrigin = minimock.CallerInfo(1)
	return mmEvaluatePolicyRuntimeEvent.mock
}

// When sets expectation for the EnforcerClient.EvaluatePolicyRuntimeEvent which will trigger the result defined by the following
// Then helper
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) When(ctx context.Context, in *mm_api.EvaluatePolicyRuntimeEventReq, opts ...grpc.CallOption) *EnforcerClientMockEvaluatePolicyRuntimeEventExpectation {
	if mmEvaluatePolicyRuntimeEvent.mock.funcEvaluatePolicyRuntimeEvent != nil {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("EnforcerClientMock.EvaluatePolicyRuntimeEvent mock is already set by Set")
	}

	expectation := &EnforcerClientMockEvaluatePolicyRuntimeEventExpectation{
		mock:               mmEvaluatePolicyRuntimeEvent.mock,
		params:             &EnforcerClientMockEvaluatePolicyRuntimeEventParams{ctx, in, opts},
		expectationOrigins: EnforcerClientMockEvaluatePolicyRuntimeEventExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmEvaluatePolicyRuntimeEvent.expectations = append(mmEvaluatePolicyRuntimeEvent.expectations, expectation)
	return expectation
}

// Then sets up EnforcerClient.EvaluatePolicyRuntimeEvent return parameters for the expectation previously defined by the When method
func (e *EnforcerClientMockEvaluatePolicyRuntimeEventExpectation) Then(ep1 *mm_api.EvaluatePolicyRuntimeEventReq, err error) *EnforcerClientMock {
	e.results = &EnforcerClientMockEvaluatePolicyRuntimeEventResults{ep1, err}
	return e.mock
}

// Times sets number of times EnforcerClient.EvaluatePolicyRuntimeEvent should be invoked
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) Times(n uint64) *mEnforcerClientMockEvaluatePolicyRuntimeEvent {
	if n == 0 {
		mmEvaluatePolicyRuntimeEvent.mock.t.Fatalf("Times of EnforcerClientMock.EvaluatePolicyRuntimeEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmEvaluatePolicyRuntimeEvent.expectedInvocations, n)
	mmEvaluatePolicyRuntimeEvent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmEvaluatePolicyRuntimeEvent
}

func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) invocationsDone() bool {
	if len(mmEvaluatePolicyRuntimeEvent.expectations) == 0 && mmEvaluatePolicyRuntimeEvent.defaultExpectation == nil && mmEvaluatePolicyRuntimeEvent.mock.funcEvaluatePolicyRuntimeEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmEvaluatePolicyRuntimeEvent.mock.afterEvaluatePolicyRuntimeEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmEvaluatePolicyRuntimeEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// EvaluatePolicyRuntimeEvent implements mm_api.EnforcerClient
func (mmEvaluatePolicyRuntimeEvent *EnforcerClientMock) EvaluatePolicyRuntimeEvent(ctx context.Context, in *mm_api.EvaluatePolicyRuntimeEventReq, opts ...grpc.CallOption) (ep1 *mm_api.EvaluatePolicyRuntimeEventReq, err error) {
	mm_atomic.AddUint64(&mmEvaluatePolicyRuntimeEvent.beforeEvaluatePolicyRuntimeEventCounter, 1)
	defer mm_atomic.AddUint64(&mmEvaluatePolicyRuntimeEvent.afterEvaluatePolicyRuntimeEventCounter, 1)

	mmEvaluatePolicyRuntimeEvent.t.Helper()

	if mmEvaluatePolicyRuntimeEvent.inspectFuncEvaluatePolicyRuntimeEvent != nil {
		mmEvaluatePolicyRuntimeEvent.inspectFuncEvaluatePolicyRuntimeEvent(ctx, in, opts...)
	}

	mm_params := EnforcerClientMockEvaluatePolicyRuntimeEventParams{ctx, in, opts}

	// Record call args
	mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.mutex.Lock()
	mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.callArgs = append(mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.callArgs, &mm_params)
	mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.mutex.Unlock()

	for _, e := range mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ep1, e.results.err
		}
	}

	if mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.defaultExpectation.Counter, 1)
		mm_want := mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.defaultExpectation.params
		mm_want_ptrs := mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.defaultExpectation.paramPtrs

		mm_got := EnforcerClientMockEvaluatePolicyRuntimeEventParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmEvaluatePolicyRuntimeEvent.t.Errorf("EnforcerClientMock.EvaluatePolicyRuntimeEvent got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmEvaluatePolicyRuntimeEvent.t.Errorf("EnforcerClientMock.EvaluatePolicyRuntimeEvent got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmEvaluatePolicyRuntimeEvent.t.Errorf("EnforcerClientMock.EvaluatePolicyRuntimeEvent got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmEvaluatePolicyRuntimeEvent.t.Errorf("EnforcerClientMock.EvaluatePolicyRuntimeEvent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmEvaluatePolicyRuntimeEvent.EvaluatePolicyRuntimeEventMock.defaultExpectation.results
		if mm_results == nil {
			mmEvaluatePolicyRuntimeEvent.t.Fatal("No results are set for the EnforcerClientMock.EvaluatePolicyRuntimeEvent")
		}
		return (*mm_results).ep1, (*mm_results).err
	}
	if mmEvaluatePolicyRuntimeEvent.funcEvaluatePolicyRuntimeEvent != nil {
		return mmEvaluatePolicyRuntimeEvent.funcEvaluatePolicyRuntimeEvent(ctx, in, opts...)
	}
	mmEvaluatePolicyRuntimeEvent.t.Fatalf("Unexpected call to EnforcerClientMock.EvaluatePolicyRuntimeEvent. %v %v %v", ctx, in, opts)
	return
}

// EvaluatePolicyRuntimeEventAfterCounter returns a count of finished EnforcerClientMock.EvaluatePolicyRuntimeEvent invocations
func (mmEvaluatePolicyRuntimeEvent *EnforcerClientMock) EvaluatePolicyRuntimeEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEvaluatePolicyRuntimeEvent.afterEvaluatePolicyRuntimeEventCounter)
}

// EvaluatePolicyRuntimeEventBeforeCounter returns a count of EnforcerClientMock.EvaluatePolicyRuntimeEvent invocations
func (mmEvaluatePolicyRuntimeEvent *EnforcerClientMock) EvaluatePolicyRuntimeEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEvaluatePolicyRuntimeEvent.beforeEvaluatePolicyRuntimeEventCounter)
}

// Calls returns a list of arguments used in each call to EnforcerClientMock.EvaluatePolicyRuntimeEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmEvaluatePolicyRuntimeEvent *mEnforcerClientMockEvaluatePolicyRuntimeEvent) Calls() []*EnforcerClientMockEvaluatePolicyRuntimeEventParams {
	mmEvaluatePolicyRuntimeEvent.mutex.RLock()

	argCopy := make([]*EnforcerClientMockEvaluatePolicyRuntimeEventParams, len(mmEvaluatePolicyRuntimeEvent.callArgs))
	copy(argCopy, mmEvaluatePolicyRuntimeEvent.callArgs)

	mmEvaluatePolicyRuntimeEvent.mutex.RUnlock()

	return argCopy
}

// MinimockEvaluatePolicyRuntimeEventDone returns true if the count of the EvaluatePolicyRuntimeEvent invocations corresponds
// the number of defined expectations
func (m *EnforcerClientMock) MinimockEvaluatePolicyRuntimeEventDone() bool {
	if m.EvaluatePolicyRuntimeEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.EvaluatePolicyRuntimeEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.EvaluatePolicyRuntimeEventMock.invocationsDone()
}

// MinimockEvaluatePolicyRuntimeEventInspect logs each unmet expectation
func (m *EnforcerClientMock) MinimockEvaluatePolicyRuntimeEventInspect() {
	for _, e := range m.EvaluatePolicyRuntimeEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to EnforcerClientMock.EvaluatePolicyRuntimeEvent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterEvaluatePolicyRuntimeEventCounter := mm_atomic.LoadUint64(&m.afterEvaluatePolicyRuntimeEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.EvaluatePolicyRuntimeEventMock.defaultExpectation != nil && afterEvaluatePolicyRuntimeEventCounter < 1 {
		if m.EvaluatePolicyRuntimeEventMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to EnforcerClientMock.EvaluatePolicyRuntimeEvent at\n%s", m.EvaluatePolicyRuntimeEventMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to EnforcerClientMock.EvaluatePolicyRuntimeEvent at\n%s with params: %#v", m.EvaluatePolicyRuntimeEventMock.defaultExpectation.expectationOrigins.origin, *m.EvaluatePolicyRuntimeEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcEvaluatePolicyRuntimeEvent != nil && afterEvaluatePolicyRuntimeEventCounter < 1 {
		m.t.Errorf("Expected call to EnforcerClientMock.EvaluatePolicyRuntimeEvent at\n%s", m.funcEvaluatePolicyRuntimeEventOrigin)
	}

	if !m.EvaluatePolicyRuntimeEventMock.invocationsDone() && afterEvaluatePolicyRuntimeEventCounter > 0 {
		m.t.Errorf("Expected %d calls to EnforcerClientMock.EvaluatePolicyRuntimeEvent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.EvaluatePolicyRuntimeEventMock.expectedInvocations), m.EvaluatePolicyRuntimeEventMock.expectedInvocationsOrigin, afterEvaluatePolicyRuntimeEventCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *EnforcerClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockEvaluatePolicyRuntimeEventInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *EnforcerClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *EnforcerClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockEvaluatePolicyRuntimeEventDone()
}
