services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.4.3
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=cs
      - CLICKHOUSE_PASSWORD=cs
      - CLICKHOUSE_DB=cs
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    networks:
      - local

  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cs
      - POSTGRES_PASSWORD=cs
      - POSTGRES_DB=cs
    healthcheck:
      test: pg_isready -U cs -d cs
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - local

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=cs
      - RABBITMQ_DEFAULT_PASS=cs
    networks:
      - local

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - local

  tetragon:
    image: quay.io/cilium/tetragon:v1.3.0
    ports:
      - "54321:54321"
    container_name: tetragon
    privileged: true
    pid: host
    volumes:
      - /sys/kernel/btf/vmlinux:/var/lib/tetragon/btf
    networks:
      - local
    command:
      - --server-address=:54321

  auth-center:
    build:
      context: ./auth-center
    image: auth-center
    ports:
      - "8080:8000"
      - "9090:9000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINISTRATOR_USERNAME: 'admin'
      ADMINISTRATOR_PASSWORD: 'admin'
      TOKEN_KEY: dd20ed6d406da2a2a325dfe6e74a3f941e94c154b0b8d15b7360e1cce46a522a
    command: --postgresAddr=postgres --logLevel=INFO
    networks:
      - local

  cluster-manager:
    build:
      context: ./cluster-manager
    image: cluster-manager
    ports:
      - "8001:8000"
      - "9001:9000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENCRYPTION_KEY=f5f3c6ac672c0e4ba49a41c96fad2cb4cb4fa2464836cada5a331847099181de
    command: --postgresAddr=postgres --logLevel=INFO
    networks:
      - local

  event-processor:
    build:
      context: ./event-processor
    image: event-processor
    ports:
      - "8002:8000"
      - "9002:9000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    command: --postgresAddr=postgres --rabbitAddr=rabbitmq --rabbitUser=cs --rabbitPassword=cs --policyEnforcerGRPCAddr=policy-enforcer:8000 --logLevel=INFO
    networks:
      - local

  history-api:
    build:
      context: ./history-api
    image: history-api
    ports:
      - "8003:8000"
      - "9003:9000"
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - ENCRYPTION_KEY=f5f3c6ac672c0e4ba49a41c96fad2cb4cb4fa2464836cada5a331847099181de
    command: --postgresAddr=postgres --clickhouseAddr=clickhouse:9000 --clickhouseUser=cs --clickhousePassword=cs --rabbitAddr=rabbitmq --rabbitUser=cs --rabbitPassword=cs --logLevel=INFO
    networks:
      - local

  notifier:
    build:
      context: ./notifier
    image: notifier
    ports:
      - "9004:9000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENCRYPTION_KEY=f5f3c6ac672c0e4ba49a41c96fad2cb4cb4fa2464836cada5a331847099181de
    command: --postgresAddr=postgres --policyEnforcerGRPCAddr=policy-enforcer:8000 --logLevel=INFO
    networks:
      - local

  policy-enforcer:
    build:
      context: ./policy-enforcer
    image: policy-enforcer
    ports:
      - "8005:8000"
      - "9005:9000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: --postgresAddr=postgres --redisAddr=redis --logLevel=INFO
    networks:
      - local

  public-api:
    build:
      context: ./public-api
    image: public-api
    ports:
      - "9006:9000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ACCESS_TOKEN_SALT=f5f3c6ac672c0e4ba49a41c96fad2cb4cb4fa2464836cada5a331847099181def5f3c6ac672c0e4ba49a41c96fad2cb4cb4fa2464836cada5a331847099181de
    command: --postgresAddr=postgres --logLevel=INFO
    networks:
      - local

  runtime-monitor:
    build:
      context: ./runtime-monitor
    image: runtime-monitor
    ports:
      - "8007:8000"
      - "9007:9000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      tetragon:
        condition: service_started
    command: --postgresAddr=postgres --rabbitAddr=rabbitmq --rabbitUser=cs --rabbitPassword=cs --tetragonAddr=tetragon:54321 --logLevel=INFO
    networks:
      - local

  cs-manager:
    build:
      context: ./cs-manager
    image: cs-manager
    ports:
      - "8008:8000"
      - "9008:9000"
    command: --postgresAddr=postgres --logLevel=INFO
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local

networks:
  local:
