apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  {{- $isChildCluster := eq (include "common.cs.isChildCluster" .) "true" }}
  env.js: |
    (function (window) {
        window['env'] = window['env'] || {};
        window['env']['isChildCluster'] = '{{ $isChildCluster }}' === 'true';
    })(this);
