apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "dup"
spec:
  kprobes:
  # SYNOPSIS
  # int do_dup2(struct files_struct *files, struct file *file, unsigned fd, unsigned flags)
  #     @files: files related to the new fd (fd that will become a copy)
  #     @file: file related to the old fd (fd being copied)
  #     @fd: file descriptor which needs to be copied
  #     @flags: flags which tweak function behaviour 
  #
  # DESCRIPTION
  # This function creates a copy of the file descriptor (fd).
  #
  # RETURN VALUE
  # On success, this function returns the new descriptor. If there is an error, the error code is returned.
  # 
  # SYSCALLS
  #     dup2(), dup3()
  # 
  - call: "do_dup2"
    syscall: false
    return: true
    args:
    - index: 1
      type: "file"
    - index: 2
      type: "int"
      label: "fd"
    returnArg:
      index: 0
      type: "int"  
    selectors:
    - matchArgs:
      - index: 2
        operator: "Equal"
        values:
        - "0" # stdin
