apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "mount"
spec:
  kprobes:
  # SYNOPSIS
  # int mount(const char *source, const char *target, const char *filesystemtype, unsigned long mountflags, const void *data);
  #     @source: filesystem backing device
  #     @target: mount point
  #     @filesystemtype: filesystem type
  #     @mountflags: mount flags
  #     @data: filesystem specific data
  #
  # DESCRIPTION
  # mount() attaches the filesystem specified by source (which is often a pathname referring to a device, 
  # but can also be the pathname of a directory or file, or a dummy string) to the location (a directory or file) 
  # specified by the pathname in target.
  #
  # RETURN VALUE
  # Returns 0 if success.
  # 
  # 
  - call: "sys_mount"
    syscall: true
    return: true
    args:
    - index: 0
      type:  "string"
    - index: 1
      type:  "string"
    returnArg:
      index: 0
      type: "int"
