apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "process-credentials"
spec:
  kprobes:
  # SYNOPSIS
  # int commit_creds(struct cred *new)
  #     @new: The credentials to be assigned
  #
  # DESCRIPTION
  # Install a new set of credentials to the current task, using RCU to replace
  # the old set.  Both the objective and the subjective credentials pointers are
  # updated.  This function may not be called if the subjective credentials are
  # in an overridden state.
  #
  # This function eats the caller's reference to the new credentials.
  #
  # RETURN VALUE
  # Always returns 0 thus allowing this function to be tail-called at the end of, say, sys_setgid().
  #
  - call: "commit_creds"
    syscall: false
    args:
    - index: 0  # The new credentials to apply
      type: "cred"
    selectors:
      - matchNamespaces:
        - namespace: Pid
          operator: NotIn
          values:
          - "host_ns"
        matchActions:
        - action: Post
          rateLimit: "1m"
