apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "rootkit"
spec:
  kprobes:
  # SYNOPSIS
  # int bpf_check(struct bpf_prog **prog, union bpf_attr *attr, bpfptr_t uattr, __u32 uattr_size);
  #     @prog: bpf program definition 
  #     @attr: bpf command attributes
  #     @uattr: userspace pointer
  #     @uattr_size: userspace union size
  #
  # DESCRIPTION
  # Run eBPF verifier.
  #
  # RETURN VALUE
  # Returns 0 if eBPF-program is valid.
  #  
  - call: "bpf_check"
    syscall: false
    return: true
    args:
    - index: 1
      type: "bpf_attr"
    returnArg:
      index: 0
      type: "int"
  # SYNOPSIS
  # unsigned long kallsyms_lookup_name(const char *name);
  #     @name: function symbol name
  #
  # DESCRIPTION
  # Lookup the address for a symbol.
  #
  # RETURN VALUE
  # Returns address of function symbol name.
  # Returns 0 if not found.
  #
  - call: "kallsyms_lookup_name"
    syscall: false
    return: false
    args:
    - index: 0
      type: "string"