apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "umh"
spec:
  kprobes:
 # SYNOPSIS
 # struct subprocess_info *call_usermodehelper_setup(const char *path, char **argv, 
 #                char **envp, gfp_t gfp_mask, 
 #                int (*init)(struct subprocess_info *info, struct cred *new), 
 #                void (*cleanup)(struct subprocess_info *info), 
 #                void *data)
 #
 #    @path: path to usermode executable
 #    @argv: arg vector for process
 #    @envp: environment for process
 #    @gfp_mask: gfp mask for memory allocation
 #    @cleanup: a cleanup function
 #    @init: an init function
 #    @data: arbitrary context sensitive data
 #
 # DESCRIPTION
 # Prepare to call a usermode helper.
 #
 # RETURN VALUE
 # Returns either %NULL on allocation failure, or a subprocess_info
 # structure.  This should be passed to call_usermodehelper_exec to
 # exec the process and free the structure.
 #
  - call: "call_usermodehelper_setup"
    syscall: false
    return: false
    args:
    - index: 0
      type: "string"
      label: "path"
 # SYNOPSIS
 # int call_usermodehelper_exec(struct subprocess_info *sub_info, int wait)
 #
 #     @sub_info: information about the subprocessa
 #     @wait: wait for the application to finish and return status.
 #        when UMH_NO_WAIT don't wait at all, but you get no useful error back
 #        when the program couldn't be exec'ed. This makes it safe to call
 #        from interrupt context.
 #
 # DESCRIPTION
 # Runs a user-space application. The application is started
 # asynchronously if wait is not set, and runs as a child of system workqueues.
 # (ie. it runs with full root capabilities and optimized affinity).
 #
 # RETURN VALUE
 # Returns 0 if success.
 # 
  - call: "call_usermodehelper_exec"
    syscall: false
    return: false
    args:
    - index: 0
      type: "string"
      label: "path"
      resolve: "path"
