apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-headless
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.mergeAnnotations" (dict "context" . "value" .Values.service.annotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: {{ .Values.service.ports.postgresql }}
      targetPort: tcp-postgresql
      protocol: TCP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
