image:
  registry: ghcr.io/runtime-radar
  repository: history-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
containerPorts:
  grpc: 8000
  http: 9000
  instrumentation: 9090
service:
  ports:
    grpc: 8000
    http: 9000
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile:
    type: "RuntimeDefault"
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
env:
  - name: RABBIT_QUEUE_PREFETCH_COUNT
    value: "100"
  - name: RUNTIME_EVENTS_BATCH_SIZE
    value: "10000"
  - name: RUNTIME_EVENTS_SAVE_INTERVAL
    value: "5s"
rabbitmq:
  enabled: true
clickhouse:
  enabled: true
serviceAccount:
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
resources:
  limits:
    cpu: 1
    memory: 1Gi
    ephemeral-storage: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 1Mi
livenessProbe:
  enabled: true
  httpGet:
    path: /live
    scheme: HTTP
    port: instrumentation
  periodSeconds: 600
  successThreshold: 1
  failureThreshold: 2
readinessProbe:
  enabled: true
  httpGet:
    path: /ready
    scheme: HTTP
    port: instrumentation
  periodSeconds: 360
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  enabled: true
  httpGet:
    path: /ready
    scheme: HTTP
    port: instrumentation
  initialDelaySeconds: 1
  periodSeconds: 3
  successThreshold: 1
  failureThreshold: 3
