apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ toJson .Values.tetragon | sha256sum }}
        {{- include "common.podAnnotations" . | indent 8 }}
      labels:
        {{- include "common.podLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      {{- if (.Values.podSecurityContext).enabled }}
      securityContext:
        {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        {{- include "container.tetragon" . | nindent 8 -}}
        {{- include "common.cs.container.app" . | nindent 8 -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      terminationGracePeriodSeconds: 1
      volumes:
      - name: cilium-run
        hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
      - name: export-logs
        hostPath:
          path: {{ .Values.exportDirectory }}
          type: DirectoryOrCreate
      - name: tetragon-config
        configMap:
          name: {{ include "common.name" . }}-tetragon-config
      - name: bpf-maps
        hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
      - name: host-proc
        hostPath:
          path: {{ .Values.tetragon.hostProcPath }}
          type: Directory
{{- if .Values.tetragon.ociHookSetup.enabled }}
      - name: oci-hooks-path
        hostPath:
          path: /usr/share/containers/oci/hooks.d/
          type: Directory
      - name: oci-hooks-install-path
        hostPath:
          path: {{ quote .Values.tetragon.ociHookSetup.installDir }}
          type: DirectoryOrCreate
{{- end }}
{{- if not .Values.tetragon.btf }}
      - emptyDir: {}
        name: metadata-files
{{- end }}
{{- range .Values.extraHostPathMounts }}
      - name: {{ .name }}
        hostPath:
          path: {{ .mountPath }}
{{- end }}
{{- with (include "common.cs.volumes" . | fromYaml) }}
      {{- toYaml .volumes | nindent 6 }}
{{- end }}
{{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
{{- end }}
