{
 "title": "Admission",
 "tags": [ "admission" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(go_goroutines,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Threats found by the detector scan",
   "type": "timeseries",
   "description": "For monitoring detectors used for checks via the admission controller. Shows the number of operation errors and duration of detector chain execution.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(detector_threats_counter{cluster=~\"$cluster\",service=\"admission-controller\"}[5m])) by (detector)",
     "legendFormat": "{{detector}}"
    }
   ]
  },
  {
   "title": "Оperating time of the entire detector chain",
   "type": "heatmap",
   "description": "Duration of event processing by the entire detector chain.\n\nNormally, the distribution should be around the middle of the hitmap. If the processing time is closer to the upper bound or regularly falls into +Inf, this may be a sign of an issue.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(operation_time_all_detectors_histogram_bucket{cluster=~\"$cluster\",service=\"admission-controller\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gRPC requests histogram",
   "type": "heatmap",
   "description": "Distribution of the gRPS request processing time in a certain range of values.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",service=~\"(admission-controller|history-api)\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}