{
 "title": "Cluster status",
 "description": "Provides information about the health of ClickHouse, RabbitMQ, and PostgreSQL, the current cluster state (central cluster, unregistered child cluster, and registered child cluster), and the license and vulnerability database update status. To get information about the health of external services, you must configure the internal Prometheus system for this purpose or install the external Prometheus system.",
 "tags": [
  "cluster",
  "cs"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(go_goroutines,cluster)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Reverse-proxy availability",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{cluster=~\"$cluster\",service=\"reverse-proxy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clickhouse availability",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "up{cluster=~\"$cluster\",service=\"clickhouse\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RabbitMQ availability",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{cluster=~\"$cluster\",service=\"rabbitmq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL availability",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "pg_up{cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(cluster_state_gauge{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"cs-manager\"})by(cluster,instance)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CS manager RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"cs-manager\"}[$interval]))",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Cluster manager RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"cluster-manager\"}[$interval]))",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  }
 ]
}