{
 "title": "CRI metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(grpc_server_handled_total,cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(grpc_server_handled_total{cluster=~\"$cluster\", service=\"container-registry-integrator\"},instance)"
    }
   },
   { "name": "interval", "query": "2m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Average time of scheduled scan",
   "type": "timeseries",
   "description": "Average time of completing a scheduled scan task. (Image scanning time is not taken into account.)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(\n  period_scan_duration_history_sum{cluster=~\"$cluster\", service=\"container-registry-integrator\"}[$interval]) / \nincrease(\n  last_periodic_scan_started_counter_total{cluster=~\"$cluster\", service=\"container-registry-integrator\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of checked images",
   "type": "timeseries",
   "description": "Number of requests to the Policy enforcer module to check if there are response rules for a specific image",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(image_check_counter_total{cluster=~\"$cluster\" ,service=\"container-registry-integrator\"}[$interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Successful/failed requests to image artifactory",
   "type": "timeseries",
   "description": "Number of successful and failed requests to image artifactories",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(success_access_to_artifactory_total{cluster=~\"$cluster\",service=\"container-registry-integrator\"}[$interval]))",
     "legendFormat": "Successful requests"
    },
    {
     "expr": "sum(increase(failed_access_to_artifactory_total{cluster=~\"$cluster\",service=\"container-registry-integrator\"}[$interval]))",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "Number of requests to scanner during scheduled scan tasks",
   "type": "timeseries",
   "description": "Number of requests to the scanner to check an image for vulnerabilities during scheduled scan tasks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(periodic_scan_counter_total{cluster=~\"$cluster\", service=\"container-registry-integrator\"}[$interval]))",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}