{
 "title": "GO applications",
 "description": "Provides the main metrics for Golang services. Shows the key performance and stability indicators for these components.",
 "tags": [ "go-app" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(go_goroutines,cluster)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(go_goroutines{cluster=~\"$cluster\"},service)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(go_goroutines{cluster=~\"$cluster\", service=~\"$service\"},instance)"
    }
   },
   { "name": "interval", "query": "2m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(go_goroutines{cluster=~\"$cluster\",job=~\"kubernetes-pods|caddy\",service=~\"$service\",instance=~\"$instance\"}) by (service,instance)",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(go_gc_duration_seconds{cluster=~\"$cluster\",job=~\"kubernetes-pods|caddy\",service=~\"$service\",instance=~\"$instance\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "CPU utilizations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{job=~\"kubernetes-pods|caddy\",cluster=~\"$cluster\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (service, instance)",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_alloc_bytes{cluster=~\"$cluster\",job=~\"kubernetes-pods|caddy\",service=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "avg(rate(go_memstats_alloc_bytes_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "avg(go_memstats_stack_inuse_bytes{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Opened FD",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=~\"kubernetes-pods|caddy\",cluster=~\"$cluster\",service=~\"$service\",instance=~\"$instance\"}) by (service,instance)",
     "legendFormat": "{{service}} - {{instance}}"
    }
   ]
  }
 ]
}