{
 "title": "GRPC requests",
 "description": "Gives a summary of gRPC communications between system services (request types and their statuses and duration). The majority of internal communications between services is done via gRPC. To make analysis easier, all related metrics are gathered in one place.",
 "tags": [ "grpc" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(grpc_server_handled_total,cluster)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(grpc_server_handled_total{cluster=~\"$cluster\"},service)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(grpc_server_handled_total{cluster=~\"$cluster\", service=~\"$service\"},instance)"
    }
   },
   { "name": "interval", "query": "2m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=\"OK\"}[$interval]))\n) / sum(rate(grpc_server_started_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\"}[$interval]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",grpc_type=~\"unary|UNARY\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (le)\n)",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "gRPC requests",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\", service=~\"$service\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=\"OK\"}[$interval]))\n/ sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\"}[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "(sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=~\"InvalidArgument|INVALID_ARGUMENT\"}[$interval])) +\nsum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=~\"NotFound|NOT_FOUND\"}[$interval])) + \nsum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=~\"AlreadyExists|ALREADY_EXISTS\"}[$interval])) + \nsum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=~\"Unauthenticated|UNAUTHENTICATED\"}[$interval])) +\nsum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=~\"PermissionDenied|PERMISSION_DENIED\"}[$interval])) + \nsum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=~\"FailedPrecondition|FAILED_PRECONDITION\"}[$interval]))\n)/ sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\"}[$interval]))",
     "legendFormat": "ClientError"
    },
    {
     "expr": "(sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=\"Internal|INTERVAL\"}[$interval])) +\nsum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=\"Unknown|UNKNOWN\"}[$interval])) + \nsum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=\"Unavailable|UNAVAILABLE\"}[$interval])) +\nsum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\",grpc_code=\"Unimplemented|UNIMPLEMENTED\"}[$interval]))\n)/ sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\"}[$interval]))",
     "legendFormat": "ServerError"
    }
   ]
  },
  {
   "title": "Status distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\"}[$interval])) by (grpc_code)\n/ ignoring(grpc_code) group_left sum(rate(grpc_server_handled_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\",grpc_type=~\"unary|UNARY\"}[$interval]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (grpc_service)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Request distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (grpc_service) \n/ ignoring(grpc_service) group_left sum(rate(grpc_server_started_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=~\"$service\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",grpc_type=~\"unary|UNARY\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (grpc_service,le)\n)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",grpc_type=~\"unary|UNARY\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",grpc_type=~\"unary|UNARY\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (le)\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",grpc_type=~\"unary|UNARY\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, \n  sum(rate(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",grpc_type=~\"unary|UNARY\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (le)\n)",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",grpc_type=~\"unary|UNARY\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, \n  sum(rate(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",grpc_type=~\"unary|UNARY\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (le)\n)",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",grpc_type=~\"unary|UNARY\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  }
 ]
}