{
 "title": "K8S management events",
 "description": "k8s management monitoring",
 "tags": [ "k8s-api" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(go_goroutines,cluster)"
    }
   },
   { "name": "event_type", "label": "Event type", "query": "add,update,delete" },
   { "name": "interval", "query": "2m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Namespace events",
   "type": "timeseries",
   "description": "Events received from Kubernetes about namespaces.\n\nThe graph shows the rate of new events generated in Kubernetes relative to the monitored elements in the cluster.\n\nWhen a new element is added, we receive an Add event, when a change occurs, an Update event, and when a deletion occurs, a Delete event.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(informer_events_count{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"kube-manager\",k8s_entity=\"namespace\",event_type=~\"$event_type\"}[$interval])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace errors",
   "type": "timeseries",
   "description": "Errors when retrieving namespace data from the Kubernetes API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(informer_errors_count{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"kube-manager\",k8s_entity=\"namespace\"}[$interval])) OR  vector(0)",
     "legendFormat": "namespace errors"
    }
   ]
  },
  {
   "title": "Node events",
   "type": "timeseries",
   "description": "Events received from Kubernetes about nodes.\n\nThe graph shows the rate of new events generated in Kubernetes relative to the monitored elements in the cluster.\n\nWhen a new element is added, we receive an Add event, when a change occurs, an Update event, and when a deletion occurs, a Delete event.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(informer_events_count{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"kube-manager\",k8s_entity=\"nodes\",event_type=~\"$event_type\"}[$interval])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node errors",
   "type": "timeseries",
   "description": "Errors when retrieving node data from the Kubernetes API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(informer_errors_count{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"kube-manager\",k8s_entity=\"nodes\"}[$interval])) OR  vector(0)",
     "legendFormat": "node errors"
    }
   ]
  },
  {
   "title": "Pod events",
   "type": "timeseries",
   "description": "Events received from Kubernetes about pods.\n\nThe graph shows the rate of new events generated in Kubernetes relative to the monitored elements in the cluster.\n\nWhen a new element is added, we receive an Add event, when a change occurs, an Update event, and when a deletion occurs, a Delete event.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(informer_events_count{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"kube-manager\",k8s_entity=\"pods\",event_type=~\"$event_type\"}[$interval])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod errors",
   "type": "timeseries",
   "description": "Errors when retrieving pod data from the Kubernetes API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(informer_errors_count{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"kube-manager\",k8s_entity=\"pods\"}[$interval])) OR  vector(0)",
     "legendFormat": "pod errors"
    }
   ]
  }
 ]
}