{
 "title": "Public-API",
 "description": "For monitoring the public API. Shows the external interface health and performance to help control its availability and quality of provided services.",
 "tags": [ "public-api" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(go_goroutines,cluster)"
    }
   },
   { "name": "interval", "query": "2m,3m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Status on the Public API service",
   "type": "timeseries",
   "description": "Timeline of requests to the public API that finished with a specified status.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\",code=\"2xx\"}[$interval]))\n/ sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\",code=\"4xx\"}[$interval]))\n/ sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\",code=\"5xx\"}[$interval]))\n/ sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Public API status distribution",
   "type": "timeseries",
   "description": "Distribution of requests with a specified status as a percentage of the total number of requests at a given time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval])) by (code)\n/ ignoring(code) group_left sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Public API RPS",
   "type": "timeseries",
   "description": "Public API RPS per endpoint.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval])) by (method,path)",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Public API request distribution",
   "type": "timeseries",
   "description": "Distribution of requests of a specific type and to a specific endpoint as a percentage of the total number of requests at a given point in time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval])) by (method,path) \n/ ignoring(method,path) group_left sum(rate(http_requests_total{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval]))",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Public API latency",
   "type": "heatmap",
   "description": "Request latencies at a given point in time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{cluster=~\"$cluster\",handler!=\"metrics\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Public API latency distribution",
   "type": "timeseries",
   "description": "Percentile of request latencies at a given point in time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval])) by (le)\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, \n  sum(rate(http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval])) by (le)\n)",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, \n  sum(rate(http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval])) by (le)\n)",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"kubernetes-pods\",service=\"public-api\"}[$interval])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  }
 ]
}