{
 "title": "Reverse proxy",
 "description": "Provides information about the availability and operation of the reverse proxy component. All internal and external requests to PT CS are routed through the reverse proxy component. The dashboard allows you to detect anomalies in the service and promptly react to possible issues.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(go_goroutines,cluster)"
    }
   },
   { "name": "interval", "query": "2m,3m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Reverse proxy success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\", code=\"200\"}[$interval]))\n) / sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Reverse proxy RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",job=\"caddy\",handler=\"static_response\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Reverse proxy latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(caddy_http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) by (le)\n)",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Status on the Reverse proxy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",handler!=\"metrics\",job=\"caddy\",code=~\"(100|101)\"}[$interval]))\n/ sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",handler!=\"metrics\",job=\"caddy\"}[$interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",handler!=\"metrics\",job=\"caddy\",code=~\"(200|201)\"}[$interval]))\n/ sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",handler!=\"metrics\",job=\"caddy\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",handler!=\"metrics\",job=\"caddy\",code=~\"(300|301|302|303|304|307|308)\"}[$interval]))\n/ sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",handler!=\"metrics\",job=\"caddy\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",handler=\"static_response\",job=\"caddy\",code=~\"(400|401|403|404|409|422|429)\"}[$interval]))\n/ sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",handler=\"static_response\",job=\"caddy\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",handler=\"static_response\",job=\"caddy\",code=~\"(500|501|502|503|504)\"}[$interval]))\n/ sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",handler=\"static_response\",job=\"caddy\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Reverse proxy RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_requests_total{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) ",
     "legendFormat": "static_response"
    }
   ]
  },
  {
   "title": "Reverse proxy latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Reverse proxy status distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) by (code)\n/ ignoring(code) group_left sum(rate(caddy_http_request_duration_seconds_count{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Reverse proxy latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(caddy_http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(caddy_http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) by (le)\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(caddy_http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, \n  sum(rate(caddy_http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) by (le)\n)",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(caddy_http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, \n  sum(rate(caddy_http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) by (le)\n)",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(caddy_http_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"caddy\",handler!=\"metrics\"}[$interval])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  }
 ]
}