{
 "title": "Runtime dashboard",
 "description": "For managing metrics of services dedicated to in-cluster deployment. If you use external components, such as RabbitMQ or ClickHouse, for correct filtering by cluster and if Grafana is configured for several clusters, add the \"cluster\" label to the metrics of these components (similar to other system metrics). You can also view information about the runtime monitor service connection to RabbitMQ.",
 "tags": [ "runtime" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(go_goroutines,cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(go_gc_duration_seconds{service=\"runtime-monitor\", cluster=~\"$cluster\"},instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "2m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Runtime Monitor producer",
   "type": "state-timeline",
   "description": "Shows whether the Runtime-Monitor service producer has a connection with RabbitMQ.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rabbit_broker_connection_state_gauge{cluster=~\"$cluster\",service=\"runtime-monitor\",queue=\"runtime_events\",is_consumer=\"false\",instance=~\"$node\"}",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Processor producer",
   "type": "state-timeline",
   "description": "Shows whether the Event-Processor service producer has a connection to RabbitMQ.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rabbit_broker_connection_state_gauge{cluster=~\"$cluster\",service=\"event-processor\",queue=\"history_events\", is_consumer=\"false\"}",
     "legendFormat": "{{cluster}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Event Processor consumer",
   "type": "state-timeline",
   "description": "Shows whether the Event-Processor service consumer has a connection to RabbitMQ.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rabbit_broker_connection_state_gauge{cluster=~\"$cluster\",service=\"event-processor\",queue=\"runtime_events\", is_consumer=\"true\"}",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "History API consumer",
   "type": "state-timeline",
   "description": "Shows whether the History-API service consumer has a connection to RabbitMQ.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rabbit_broker_connection_state_gauge{cluster=~\"$cluster\",service=\"history-api\",queue=\"history_events\", is_consumer=\"true\"}",
     "legendFormat": "{{cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Detectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Detector operating time",
     "type": "timeseries",
     "description": "Event processing time per detector.\n\nIf the duration is significantly higher than the average number, this may indicate an issue.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(operation_time_one_detector_histogram_sum{cluster=~\"$cluster\",service=\"event-processor\"}[5m])/ rate(operation_time_one_detector_histogram_count{cluster=~\"$cluster\",service=\"event-processor\"}[$interval])) by (detector)",
       "legendFormat": "{{detector}}"
      }
     ]
    },
    {
     "title": "Оperating time of the entire detector chain",
     "type": "heatmap",
     "description": "Duration of event processing by the entire detector chain.\n\nNormally, the distribution should be around the middle of the hitmap. If the processing time is closer to the upper bound or regularly falls into +Inf, this may be a sign of an issue.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "sum(rate(operation_time_all_detectors_histogram_bucket{cluster=~\"$cluster\",service=\"event-processor\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Tetragon events buffer size",
     "type": "timeseries",
     "description": "The Runtime-Monitor service has an internal buffer for Tetragon events. It is designed to smooth out peaks in the load on the RabbitMQ queue provider.\n\nIf everything runs properly, in most cases, the size of this buffer will be around zero. If the size reaches the maximum value (1,000 by default), there may be an issue.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "avg(tetragon_events_buffer_size_gauge{cluster=~\"$cluster\",instance=~\"$node\"}) by (cluster,instance)",
       "legendFormat": "{{cluster}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Tetragon events dropped count",
     "type": "timeseries",
     "description": "The Runtime-Monitor service has an internal buffer for Tetragon events. It is designed to smooth out peaks in the load on the RabbitMQ queue provider.\n\nWhen the buffer is full, the following Tetragon messages will be lost. This metric shows the number of lost events.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "expr": "sum(rate(tetragon_events_dropped_count{cluster=~\"$cluster\",instance=~\"$node\"}[$interval])) by (cluster,instance)",
       "legendFormat": "{{cluster}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Threats found by the detector scan",
     "type": "timeseries",
     "description": "Threats found during event analysis by detectors in time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "sum(increase(detector_threats_counter{cluster=~\"$cluster\",service=\"event-processor\"}[$interval])) by (detector)",
       "legendFormat": "{{detector}}"
      }
     ]
    },
    {
     "title": "Detector calls that ended in errors",
     "type": "timeseries",
     "description": "Shows detector errors.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "expr": "sum(increase(detector_errors_counter{cluster=~\"$cluster\",service=\"event-processor\"}[$interval])) by (detector)",
       "legendFormat": "{{detector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue size of events prepared for processing (Rabbit)",
     "type": "timeseries",
     "description": "The size of the event queue to be processed.\n\nEvents are processed by the Event-Processor service.\nIf the queue size grows, it means that Event-Processor cannot handle the load.\n\nCheck for errors in the logs and scale the Event-processor service accordingly.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(rabbitmq_queue_messages{queue=\"runtime_events\",cluster=~\"$cluster\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Rate of adding new events to rabbit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "targets": [
      {
       "expr": "sum(rate(rabbit_add_events_success_count{cluster=~\"$cluster\", instance=~\"$node\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failure rate when adding new events in Rabbit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "expr": "sum(rate(rabbit_add_events_failure_count{cluster=~\"$cluster\",instance=~\"$node\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "History events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue size of history events after processing (Rabbit)",
     "type": "timeseries",
     "description": "The size of the queue of processed events to be sent.\n\nEvents are sent by the History-API service.\nIf the queue size grows, it means that the History-API cannot handle the load.\n\nCheck for errors in the logs and scale the History-API service accordingly.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "avg(rabbitmq_queue_messages{queue=\"history_events\",cluster=~\"$cluster\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Rate of adding history events to rabbit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(rabbit_add_history_success_count{cluster=~\"$cluster\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failure rate when adding history events in Rabbit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(rabbit_add_history_failure_count{cluster=~\"$cluster\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC requests histogram",
   "type": "heatmap",
   "description": "Distribution of the gRPS request processing time in a certain range of values.",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handling_seconds_bucket{cluster=~\"$cluster\", service=~\"(runtime-monitor|policy-enforcer|event-processor|history-api)\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Clickhouse activity",
   "type": "timeseries",
   "description": "Processed events are sent to ClickHouse.\n\nThis graph shows the overall ClickHouse activity as well as the read and write speed.\n\nIf there is no activity, events are being processed and queued in RabbitMQ, or the speed is too low, this may indicate issues with the ClickHouse database.",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(ClickHouseProfileEvents_Query{cluster=~\"$cluster\"}[$interval])) by (cluster)",
     "legendFormat": "{{cluster}} "
    }
   ]
  }
 ]
}