services:
  mailpit:
    extends:
      file: ../docker-compose.yml
      service: mailpit

  syslog-ng:
    extends:
      file: ../docker-compose.yml
      service: syslog-ng

  postgres:
    extends:
      file: ../docker-compose.test.yml
      service: postgres

  test:
    extends:
      file: ../docker-compose.test.yml
      service: test
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
      syslog-ng:
        condition: service_started
    networks:
      - local
    environment:
      - COMPONENT=notifier
      - TEST_MAILPIT_HTTP_ADDR=http://mailpit:8025
      - TEST_MAILPIT_SMTP_ADDR=mailpit:1025
      - TEST_SYSLOG_UDP_ADDR=udp://syslog-ng:6514
      - TEST_SYSLOG_TCP_ADDR=tcp://syslog-ng:6601

networks:
  local:
