services:
  mailpit:
    extends:
      file: docker-compose.yml
      service: mailpit

  syslog-ng:
    extends:
      file: docker-compose.yml
      service: syslog-ng

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    environment:
      - POSTGRES_DB=cs_test

  test:
    image: golang:1.24
    working_dir: /go/src/repo
    volumes:
      - .:/go/src/repo
    depends_on:
      - postgres
      - mailpit
      - syslog-ng
    networks:
      - local
    environment:
      - POSTGRES_ADDR=postgres
      - TEST_MAILPIT_HTTP_ADDR=http://mailpit:8025
      - TEST_MAILPIT_SMTP_ADDR=mailpit:1025
      - TEST_SYSLOG_UDP_ADDR=udp://syslog-ng:6514
      - TEST_SYSLOG_TCP_ADDR=tcp://syslog-ng:6601

    command: "go test -race -count=1 -vet=off ./..."

networks:
  local:
