{{- $tlsEnabled := eq (include "common.tls.enabled" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.mergeAnnotations" (dict "context" . "value" .Values.service.annotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      targetPort: http
      port: {{ .Values.service.ports.http }}
      protocol: TCP
    - name: grpc
      targetPort: grpc
      port: {{ .Values.service.ports.grpc }}
      protocol: TCP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
