image:
  registry: ghcr.io/runtime-radar
  repository: cs-manager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
containerPorts:
  grpc: 8000
  http: 9000
  instrumentation: 9090
service:
  ports:
    grpc: 8000
    http: 9000
isChildCluster: false
ownCsUrl: ""
centralCsUrl: ""
checksumFields: [flusUrl]
registrationToken: ""
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile:
    type: "RuntimeDefault"
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
env:
  - name: PROXY_URL
    value: "{{ .Values.flusProxyUrl }}"
  - name: REGISTRATION_TOKEN
    value: "{{ .Values.registrationToken }}"
postgresql:
  enabled: true
serviceAccount:
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
resources:
  limits:
    cpu: 300m
    memory: 1Gi
    ephemeral-storage: 10Gi
  requests:
    cpu: 150m
    memory: 512Mi
    ephemeral-storage: 1Gi
livenessProbe:
  enabled: true
  httpGet:
    path: /live
    scheme: HTTP
    port: instrumentation
  periodSeconds: 600
  successThreshold: 1
  failureThreshold: 2
readinessProbe:
  enabled: true
  httpGet:
    path: /ready
    scheme: HTTP
    port: instrumentation
  periodSeconds: 360
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  enabled: true
  httpGet:
    path: /ready
    scheme: HTTP
    port: instrumentation
  initialDelaySeconds: 1
  periodSeconds: 3
  successThreshold: 1
  failureThreshold: 3
