// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: kube_config.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Config        *Config_ConfigJSON     `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_kube_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_kube_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_kube_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Config) GetConfig() *Config_ConfigJSON {
	if x != nil {
		return x.Config
	}
	return nil
}

type Config_ConfigJSON struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// allow_list specifies a list of namespaces used for tracking Kubernetes.
	// If the namespace list is empty, the list of denied namespaces is applied.
	AllowList *Config_ConfigJSON_Filter `protobuf:"bytes,4,opt,name=allow_list,json=allowList,proto3" json:"allow_list,omitempty"`
	// deny_list specifies a list of namespaces that should not be used for tracking Kubernetes.
	// If both allow_list and deny_list filters are specified,
	// allow_list is applied as the more specific and narrow list.
	//
	// If both lists are empty, all available namespaces will be tracked.
	DenyList      *Config_ConfigJSON_Filter `protobuf:"bytes,5,opt,name=deny_list,json=denyList,proto3" json:"deny_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config_ConfigJSON) Reset() {
	*x = Config_ConfigJSON{}
	mi := &file_kube_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_ConfigJSON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_ConfigJSON) ProtoMessage() {}

func (x *Config_ConfigJSON) ProtoReflect() protoreflect.Message {
	mi := &file_kube_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_ConfigJSON.ProtoReflect.Descriptor instead.
func (*Config_ConfigJSON) Descriptor() ([]byte, []int) {
	return file_kube_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Config_ConfigJSON) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Config_ConfigJSON) GetAllowList() *Config_ConfigJSON_Filter {
	if x != nil {
		return x.AllowList
	}
	return nil
}

func (x *Config_ConfigJSON) GetDenyList() *Config_ConfigJSON_Filter {
	if x != nil {
		return x.DenyList
	}
	return nil
}

type Config_ConfigJSON_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config_ConfigJSON_Filter) Reset() {
	*x = Config_ConfigJSON_Filter{}
	mi := &file_kube_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_ConfigJSON_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_ConfigJSON_Filter) ProtoMessage() {}

func (x *Config_ConfigJSON_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_kube_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_ConfigJSON_Filter.ProtoReflect.Descriptor instead.
func (*Config_ConfigJSON_Filter) Descriptor() ([]byte, []int) {
	return file_kube_config_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Config_ConfigJSON_Filter) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

var File_kube_config_proto protoreflect.FileDescriptor

const file_kube_config_proto_rawDesc = "" +
	"\n" +
	"\x11kube_config.proto\x12\vkube_config\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb9\x02\n" +
	"\x06Config\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x06config\x18\x04 \x01(\v2\x1e.kube_config.Config.ConfigJSONR\x06config\x1a\xda\x01\n" +
	"\n" +
	"ConfigJSON\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12D\n" +
	"\n" +
	"allow_list\x18\x04 \x01(\v2%.kube_config.Config.ConfigJSON.FilterR\tallowList\x12B\n" +
	"\tdeny_list\x18\x05 \x01(\v2%.kube_config.Config.ConfigJSON.FilterR\bdenyList\x1a(\n" +
	"\x06Filter\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespacesJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x042\xc8\x01\n" +
	"\x10ConfigController\x12Z\n" +
	"\x03Add\x12\x13.kube_config.Config\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/config/kube-manager\x12X\n" +
	"\x04Read\x12\x16.google.protobuf.Empty\x1a\x13.kube_config.Config\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/config/kube-managerB%\x92A\x1b\x12\x19\n" +
	"\x17Kube Manager Config APIZ\x05./apib\x06proto3"

var (
	file_kube_config_proto_rawDescOnce sync.Once
	file_kube_config_proto_rawDescData []byte
)

func file_kube_config_proto_rawDescGZIP() []byte {
	file_kube_config_proto_rawDescOnce.Do(func() {
		file_kube_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kube_config_proto_rawDesc), len(file_kube_config_proto_rawDesc)))
	})
	return file_kube_config_proto_rawDescData
}

var file_kube_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kube_config_proto_goTypes = []any{
	(*Config)(nil),                   // 0: kube_config.Config
	(*Config_ConfigJSON)(nil),        // 1: kube_config.Config.ConfigJSON
	(*Config_ConfigJSON_Filter)(nil), // 2: kube_config.Config.ConfigJSON.Filter
	(*emptypb.Empty)(nil),            // 3: google.protobuf.Empty
}
var file_kube_config_proto_depIdxs = []int32{
	1, // 0: kube_config.Config.config:type_name -> kube_config.Config.ConfigJSON
	2, // 1: kube_config.Config.ConfigJSON.allow_list:type_name -> kube_config.Config.ConfigJSON.Filter
	2, // 2: kube_config.Config.ConfigJSON.deny_list:type_name -> kube_config.Config.ConfigJSON.Filter
	0, // 3: kube_config.ConfigController.Add:input_type -> kube_config.Config
	3, // 4: kube_config.ConfigController.Read:input_type -> google.protobuf.Empty
	3, // 5: kube_config.ConfigController.Add:output_type -> google.protobuf.Empty
	0, // 6: kube_config.ConfigController.Read:output_type -> kube_config.Config
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kube_config_proto_init() }
func file_kube_config_proto_init() {
	if File_kube_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kube_config_proto_rawDesc), len(file_kube_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kube_config_proto_goTypes,
		DependencyIndexes: file_kube_config_proto_depIdxs,
		MessageInfos:      file_kube_config_proto_msgTypes,
	}.Build()
	File_kube_config_proto = out.File
	file_kube_config_proto_goTypes = nil
	file_kube_config_proto_depIdxs = nil
}
