// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pod.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/runtime-radar/runtime-radar/kube-manager/api/k8s.io/api/core/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPodReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodReq) Reset() {
	*x = GetPodReq{}
	mi := &file_pod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodReq) ProtoMessage() {}

func (x *GetPodReq) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodReq.ProtoReflect.Descriptor instead.
func (*GetPodReq) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{0}
}

func (x *GetPodReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPodReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetPodResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           *v1.Pod                `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodResp) Reset() {
	*x = GetPodResp{}
	mi := &file_pod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodResp) ProtoMessage() {}

func (x *GetPodResp) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodResp.ProtoReflect.Descriptor instead.
func (*GetPodResp) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{1}
}

func (x *GetPodResp) GetPod() *v1.Pod {
	if x != nil {
		return x.Pod
	}
	return nil
}

type ListPodMetaReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// By default, the results will be sorted by namespace+name,
	// but if necessary, you can also sort by name or creation date
	// Possible sorting options:
	// name, created_at
	Sort *Sort `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	// The Namespaces parameter only supports a list of exact values.
	Namespaces []string `protobuf:"bytes,10,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// Node, Pod, and Container parameters can contain extract values or part of the name and support templating.
	// For example: pod-name-*
	Nodes         []string `protobuf:"bytes,11,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Pods          []string `protobuf:"bytes,12,rep,name=pods,proto3" json:"pods,omitempty"`
	Containers    []string `protobuf:"bytes,13,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodMetaReq) Reset() {
	*x = ListPodMetaReq{}
	mi := &file_pod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodMetaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodMetaReq) ProtoMessage() {}

func (x *ListPodMetaReq) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodMetaReq.ProtoReflect.Descriptor instead.
func (*ListPodMetaReq) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{2}
}

func (x *ListPodMetaReq) GetSort() *Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListPodMetaReq) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ListPodMetaReq) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListPodMetaReq) GetPods() []string {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *ListPodMetaReq) GetContainers() []string {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ListPodMetaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pods          []*ListPodMetaResp_Pod `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodMetaResp) Reset() {
	*x = ListPodMetaResp{}
	mi := &file_pod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodMetaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodMetaResp) ProtoMessage() {}

func (x *ListPodMetaResp) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodMetaResp.ProtoReflect.Descriptor instead.
func (*ListPodMetaResp) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{3}
}

func (x *ListPodMetaResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPodMetaResp) GetPods() []*ListPodMetaResp_Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

type ListPodPageReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// By default, the results will be sorted by namespace+name,
	// but if necessary, you can also sort by name or creation date
	// Possible sorting options:
	// name, created_at
	Sort     *Sort  `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	PageNum  uint32 `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The Namespaces parameter only supports a list of exact values.
	Namespaces []string `protobuf:"bytes,10,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// Node, Pod, and Container parameters can contain extract values or part of the name and support templating.
	// For example: pod-name-*
	Nodes         []string `protobuf:"bytes,11,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Pods          []string `protobuf:"bytes,12,rep,name=pods,proto3" json:"pods,omitempty"`
	Containers    []string `protobuf:"bytes,13,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodPageReq) Reset() {
	*x = ListPodPageReq{}
	mi := &file_pod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodPageReq) ProtoMessage() {}

func (x *ListPodPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodPageReq.ProtoReflect.Descriptor instead.
func (*ListPodPageReq) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{4}
}

func (x *ListPodPageReq) GetSort() *Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListPodPageReq) GetPageNum() uint32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListPodPageReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPodPageReq) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ListPodPageReq) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListPodPageReq) GetPods() []string {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *ListPodPageReq) GetContainers() []string {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ListPodPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          []*v1.Pod              `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodPageResp) Reset() {
	*x = ListPodPageResp{}
	mi := &file_pod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodPageResp) ProtoMessage() {}

func (x *ListPodPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodPageResp.ProtoReflect.Descriptor instead.
func (*ListPodPageResp) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{5}
}

func (x *ListPodPageResp) GetPods() []*v1.Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *ListPodPageResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type KillPodReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillPodReq) Reset() {
	*x = KillPodReq{}
	mi := &file_pod_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillPodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillPodReq) ProtoMessage() {}

func (x *KillPodReq) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillPodReq.ProtoReflect.Descriptor instead.
func (*KillPodReq) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{6}
}

func (x *KillPodReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KillPodReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListPodMetaResp_Pod struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Uid       string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	NodeName  string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// The phase of a Pod is a simple, high-level summary of where the Pod is in its lifecycle.
	// There are five possible phase values:
	// Pending, Running, Succeeded, Failed, Unknown
	Phase         string                           `protobuf:"bytes,5,opt,name=phase,proto3" json:"phase,omitempty"`
	Containers    []*ListPodMetaResp_Pod_Container `protobuf:"bytes,10,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodMetaResp_Pod) Reset() {
	*x = ListPodMetaResp_Pod{}
	mi := &file_pod_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodMetaResp_Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodMetaResp_Pod) ProtoMessage() {}

func (x *ListPodMetaResp_Pod) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodMetaResp_Pod.ProtoReflect.Descriptor instead.
func (*ListPodMetaResp_Pod) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListPodMetaResp_Pod) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ListPodMetaResp_Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPodMetaResp_Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListPodMetaResp_Pod) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ListPodMetaResp_Pod) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ListPodMetaResp_Pod) GetContainers() []*ListPodMetaResp_Pod_Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ListPodMetaResp_Pod_Owner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scannable     bool                   `protobuf:"varint,3,opt,name=scannable,proto3" json:"scannable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodMetaResp_Pod_Owner) Reset() {
	*x = ListPodMetaResp_Pod_Owner{}
	mi := &file_pod_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodMetaResp_Pod_Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodMetaResp_Pod_Owner) ProtoMessage() {}

func (x *ListPodMetaResp_Pod_Owner) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodMetaResp_Pod_Owner.ProtoReflect.Descriptor instead.
func (*ListPodMetaResp_Pod_Owner) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *ListPodMetaResp_Pod_Owner) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListPodMetaResp_Pod_Owner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPodMetaResp_Pod_Owner) GetScannable() bool {
	if x != nil {
		return x.Scannable
	}
	return false
}

type ListPodMetaResp_Pod_Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	ImageDigest   string                 `protobuf:"bytes,3,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodMetaResp_Pod_Container) Reset() {
	*x = ListPodMetaResp_Pod_Container{}
	mi := &file_pod_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodMetaResp_Pod_Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodMetaResp_Pod_Container) ProtoMessage() {}

func (x *ListPodMetaResp_Pod_Container) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodMetaResp_Pod_Container.ProtoReflect.Descriptor instead.
func (*ListPodMetaResp_Pod_Container) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{3, 0, 1}
}

func (x *ListPodMetaResp_Pod_Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPodMetaResp_Pod_Container) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *ListPodMetaResp_Pod_Container) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

var File_pod_proto protoreflect.FileDescriptor

const file_pod_proto_rawDesc = "" +
	"\n" +
	"\tpod.proto\x12\x03pod\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\"k8s.io/api/core/v1/generated.proto\x1a\n" +
	"kube.proto\"=\n" +
	"\tGetPodReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"7\n" +
	"\n" +
	"GetPodResp\x12)\n" +
	"\x03pod\x18\x01 \x01(\v2\x17.k8s.io.api.core.v1.PodR\x03pod\"\x9a\x01\n" +
	"\x0eListPodMetaReq\x12\x1e\n" +
	"\x04sort\x18\x01 \x01(\v2\n" +
	".kube.SortR\x04sort\x12\x1e\n" +
	"\n" +
	"namespaces\x18\n" +
	" \x03(\tR\n" +
	"namespaces\x12\x14\n" +
	"\x05nodes\x18\v \x03(\tR\x05nodes\x12\x12\n" +
	"\x04pods\x18\f \x03(\tR\x04pods\x12\x1e\n" +
	"\n" +
	"containers\x18\r \x03(\tR\n" +
	"containers\"\xc8\x03\n" +
	"\x0fListPodMetaResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12,\n" +
	"\x04pods\x18\x02 \x03(\v2\x18.pod.ListPodMetaResp.PodR\x04pods\x1a\xf0\x02\n" +
	"\x03Pod\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05phase\x18\x05 \x01(\tR\x05phase\x12B\n" +
	"\n" +
	"containers\x18\n" +
	" \x03(\v2\".pod.ListPodMetaResp.Pod.ContainerR\n" +
	"containers\x1aM\n" +
	"\x05Owner\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tscannable\x18\x03 \x01(\bR\tscannable\x1a_\n" +
	"\tContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\x12!\n" +
	"\fimage_digest\x18\x03 \x01(\tR\vimageDigest\"\xd2\x01\n" +
	"\x0eListPodPageReq\x12\x1e\n" +
	"\x04sort\x18\x01 \x01(\v2\n" +
	".kube.SortR\x04sort\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\rR\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x1e\n" +
	"\n" +
	"namespaces\x18\n" +
	" \x03(\tR\n" +
	"namespaces\x12\x14\n" +
	"\x05nodes\x18\v \x03(\tR\x05nodes\x12\x12\n" +
	"\x04pods\x18\f \x03(\tR\x04pods\x12\x1e\n" +
	"\n" +
	"containers\x18\r \x03(\tR\n" +
	"containers\"T\n" +
	"\x0fListPodPageResp\x12+\n" +
	"\x04pods\x18\x01 \x03(\v2\x17.k8s.io.api.core.v1.PodR\x04pods\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\">\n" +
	"\n" +
	"KillPodReq\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xda\x02\n" +
	"\rPodController\x12;\n" +
	"\x03Get\x12\x0e.pod.GetPodReq\x1a\x0f.pod.GetPodResp\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/api/v1/pod\x12O\n" +
	"\bListMeta\x12\x13.pod.ListPodMetaReq\x1a\x14.pod.ListPodMetaResp\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/pod/list\x12Z\n" +
	"\bListPage\x12\x13.pod.ListPodPageReq\x1a\x14.pod.ListPodPageResp\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/pod/page/{page_num}\x12_\n" +
	"\x04Kill\x12\x0f.pod.KillPodReq\x1a\x16.google.protobuf.Empty\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/pod/{namespace}/{name}/killB0\x92A&\x12$\n" +
	"\vK8S Pod API\"\x15\x1a\x13ptcs@ptsecurity.comZ\x05./apib\x06proto3"

var (
	file_pod_proto_rawDescOnce sync.Once
	file_pod_proto_rawDescData []byte
)

func file_pod_proto_rawDescGZIP() []byte {
	file_pod_proto_rawDescOnce.Do(func() {
		file_pod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pod_proto_rawDesc), len(file_pod_proto_rawDesc)))
	})
	return file_pod_proto_rawDescData
}

var file_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pod_proto_goTypes = []any{
	(*GetPodReq)(nil),                     // 0: pod.GetPodReq
	(*GetPodResp)(nil),                    // 1: pod.GetPodResp
	(*ListPodMetaReq)(nil),                // 2: pod.ListPodMetaReq
	(*ListPodMetaResp)(nil),               // 3: pod.ListPodMetaResp
	(*ListPodPageReq)(nil),                // 4: pod.ListPodPageReq
	(*ListPodPageResp)(nil),               // 5: pod.ListPodPageResp
	(*KillPodReq)(nil),                    // 6: pod.KillPodReq
	(*ListPodMetaResp_Pod)(nil),           // 7: pod.ListPodMetaResp.Pod
	(*ListPodMetaResp_Pod_Owner)(nil),     // 8: pod.ListPodMetaResp.Pod.Owner
	(*ListPodMetaResp_Pod_Container)(nil), // 9: pod.ListPodMetaResp.Pod.Container
	(*v1.Pod)(nil),                        // 10: k8s.io.api.core.v1.Pod
	(*Sort)(nil),                          // 11: kube.Sort
	(*emptypb.Empty)(nil),                 // 12: google.protobuf.Empty
}
var file_pod_proto_depIdxs = []int32{
	10, // 0: pod.GetPodResp.pod:type_name -> k8s.io.api.core.v1.Pod
	11, // 1: pod.ListPodMetaReq.sort:type_name -> kube.Sort
	7,  // 2: pod.ListPodMetaResp.pods:type_name -> pod.ListPodMetaResp.Pod
	11, // 3: pod.ListPodPageReq.sort:type_name -> kube.Sort
	10, // 4: pod.ListPodPageResp.pods:type_name -> k8s.io.api.core.v1.Pod
	9,  // 5: pod.ListPodMetaResp.Pod.containers:type_name -> pod.ListPodMetaResp.Pod.Container
	0,  // 6: pod.PodController.Get:input_type -> pod.GetPodReq
	2,  // 7: pod.PodController.ListMeta:input_type -> pod.ListPodMetaReq
	4,  // 8: pod.PodController.ListPage:input_type -> pod.ListPodPageReq
	6,  // 9: pod.PodController.Kill:input_type -> pod.KillPodReq
	1,  // 10: pod.PodController.Get:output_type -> pod.GetPodResp
	3,  // 11: pod.PodController.ListMeta:output_type -> pod.ListPodMetaResp
	5,  // 12: pod.PodController.ListPage:output_type -> pod.ListPodPageResp
	12, // 13: pod.PodController.Kill:output_type -> google.protobuf.Empty
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pod_proto_init() }
func file_pod_proto_init() {
	if File_pod_proto != nil {
		return
	}
	file_kube_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pod_proto_rawDesc), len(file_pod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pod_proto_goTypes,
		DependencyIndexes: file_pod_proto_depIdxs,
		MessageInfos:      file_pod_proto_msgTypes,
	}.Build()
	File_pod_proto = out.File
	file_pod_proto_goTypes = nil
	file_pod_proto_depIdxs = nil
}
