// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: pod.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodController_Get_FullMethodName      = "/pod.PodController/Get"
	PodController_ListMeta_FullMethodName = "/pod.PodController/ListMeta"
	PodController_ListPage_FullMethodName = "/pod.PodController/ListPage"
)

// PodControllerClient is the client API for PodController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The PodController service definition.
type PodControllerClient interface {
	Get(ctx context.Context, in *GetPodReq, opts ...grpc.CallOption) (*GetPodResp, error)
	ListMeta(ctx context.Context, in *ListPodMetaReq, opts ...grpc.CallOption) (*ListPodMetaResp, error)
	ListPage(ctx context.Context, in *ListPodPageReq, opts ...grpc.CallOption) (*ListPodPageResp, error)
}

type podControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewPodControllerClient(cc grpc.ClientConnInterface) PodControllerClient {
	return &podControllerClient{cc}
}

func (c *podControllerClient) Get(ctx context.Context, in *GetPodReq, opts ...grpc.CallOption) (*GetPodResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPodResp)
	err := c.cc.Invoke(ctx, PodController_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podControllerClient) ListMeta(ctx context.Context, in *ListPodMetaReq, opts ...grpc.CallOption) (*ListPodMetaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPodMetaResp)
	err := c.cc.Invoke(ctx, PodController_ListMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podControllerClient) ListPage(ctx context.Context, in *ListPodPageReq, opts ...grpc.CallOption) (*ListPodPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPodPageResp)
	err := c.cc.Invoke(ctx, PodController_ListPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodControllerServer is the server API for PodController service.
// All implementations must embed UnimplementedPodControllerServer
// for forward compatibility.
//
// The PodController service definition.
type PodControllerServer interface {
	Get(context.Context, *GetPodReq) (*GetPodResp, error)
	ListMeta(context.Context, *ListPodMetaReq) (*ListPodMetaResp, error)
	ListPage(context.Context, *ListPodPageReq) (*ListPodPageResp, error)
	mustEmbedUnimplementedPodControllerServer()
}

// UnimplementedPodControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodControllerServer struct{}

func (UnimplementedPodControllerServer) Get(context.Context, *GetPodReq) (*GetPodResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPodControllerServer) ListMeta(context.Context, *ListPodMetaReq) (*ListPodMetaResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMeta not implemented")
}
func (UnimplementedPodControllerServer) ListPage(context.Context, *ListPodPageReq) (*ListPodPageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPage not implemented")
}
func (UnimplementedPodControllerServer) mustEmbedUnimplementedPodControllerServer() {}
func (UnimplementedPodControllerServer) testEmbeddedByValue()                       {}

// UnsafePodControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodControllerServer will
// result in compilation errors.
type UnsafePodControllerServer interface {
	mustEmbedUnimplementedPodControllerServer()
}

func RegisterPodControllerServer(s grpc.ServiceRegistrar, srv PodControllerServer) {
	// If the following call pancis, it indicates UnimplementedPodControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodController_ServiceDesc, srv)
}

func _PodController_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodControllerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodController_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodControllerServer).Get(ctx, req.(*GetPodReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodController_ListMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodMetaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodControllerServer).ListMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodController_ListMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodControllerServer).ListMeta(ctx, req.(*ListPodMetaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodController_ListPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodControllerServer).ListPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodController_ListPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodControllerServer).ListPage(ctx, req.(*ListPodPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PodController_ServiceDesc is the grpc.ServiceDesc for PodController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pod.PodController",
	HandlerType: (*PodControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _PodController_Get_Handler,
		},
		{
			MethodName: "ListMeta",
			Handler:    _PodController_ListMeta_Handler,
		},
		{
			MethodName: "ListPage",
			Handler:    _PodController_ListPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pod.proto",
}
