// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: runtime_stats.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeEventsCounterReq struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Period *Period                `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	// type represents the type of runtime event registered in the system.
	// Possible values are UNDEF, PROCESS_EXEC, PROCESS_EXIT, PROCESS_KPROBE, PROCESS_TRACEPOINT, PROCESS_LOADER and PROCESS_UPROBE
	Type          *string `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEventsCounterReq) Reset() {
	*x = RuntimeEventsCounterReq{}
	mi := &file_runtime_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEventsCounterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEventsCounterReq) ProtoMessage() {}

func (x *RuntimeEventsCounterReq) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEventsCounterReq.ProtoReflect.Descriptor instead.
func (*RuntimeEventsCounterReq) Descriptor() ([]byte, []int) {
	return file_runtime_stats_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeEventsCounterReq) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *RuntimeEventsCounterReq) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

type DetectorRatingReq struct {
	state  protoimpl.MessageState    `protogen:"open.v1"`
	Filter *DetectorRatingReq_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Period *Period                   `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	// top-N items should be returned
	Count int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// sort by default: severity desc, count desc
	Sorts         []*Sort `protobuf:"bytes,4,rep,name=sorts,proto3" json:"sorts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorRatingReq) Reset() {
	*x = DetectorRatingReq{}
	mi := &file_runtime_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorRatingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorRatingReq) ProtoMessage() {}

func (x *DetectorRatingReq) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorRatingReq.ProtoReflect.Descriptor instead.
func (*DetectorRatingReq) Descriptor() ([]byte, []int) {
	return file_runtime_stats_proto_rawDescGZIP(), []int{1}
}

func (x *DetectorRatingReq) GetFilter() *DetectorRatingReq_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DetectorRatingReq) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *DetectorRatingReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DetectorRatingReq) GetSorts() []*Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

type DetectorRatingResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// detector rating by severity and number of detections
	Counters      []*DetectorRatingResp_Counter `protobuf:"bytes,1,rep,name=counters,proto3" json:"counters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorRatingResp) Reset() {
	*x = DetectorRatingResp{}
	mi := &file_runtime_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorRatingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorRatingResp) ProtoMessage() {}

func (x *DetectorRatingResp) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorRatingResp.ProtoReflect.Descriptor instead.
func (*DetectorRatingResp) Descriptor() ([]byte, []int) {
	return file_runtime_stats_proto_rawDescGZIP(), []int{2}
}

func (x *DetectorRatingResp) GetCounters() []*DetectorRatingResp_Counter {
	if x != nil {
		return x.Counters
	}
	return nil
}

type DetectorRatingReq_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	ContainerName string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorRatingReq_Filter) Reset() {
	*x = DetectorRatingReq_Filter{}
	mi := &file_runtime_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorRatingReq_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorRatingReq_Filter) ProtoMessage() {}

func (x *DetectorRatingReq_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorRatingReq_Filter.ProtoReflect.Descriptor instead.
func (*DetectorRatingReq_Filter) Descriptor() ([]byte, []int) {
	return file_runtime_stats_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DetectorRatingReq_Filter) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *DetectorRatingReq_Filter) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *DetectorRatingReq_Filter) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type DetectorRatingResp_Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetectorId    string                 `protobuf:"bytes,1,opt,name=detector_id,json=detectorId,proto3" json:"detector_id,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorRatingResp_Counter) Reset() {
	*x = DetectorRatingResp_Counter{}
	mi := &file_runtime_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorRatingResp_Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorRatingResp_Counter) ProtoMessage() {}

func (x *DetectorRatingResp_Counter) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorRatingResp_Counter.ProtoReflect.Descriptor instead.
func (*DetectorRatingResp_Counter) Descriptor() ([]byte, []int) {
	return file_runtime_stats_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DetectorRatingResp_Counter) GetDetectorId() string {
	if x != nil {
		return x.DetectorId
	}
	return ""
}

func (x *DetectorRatingResp_Counter) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *DetectorRatingResp_Counter) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_runtime_stats_proto protoreflect.FileDescriptor

const file_runtime_stats_proto_rawDesc = "" +
	"\n" +
	"\x13runtime_stats.proto\x12\rruntime_stats\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\fcommon.proto\"c\n" +
	"\x17RuntimeEventsCounterReq\x12&\n" +
	"\x06period\x18\x01 \x01(\v2\x0e.common.PeriodR\x06period\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x00R\x04type\x88\x01\x01B\a\n" +
	"\x05_type\"\xa7\x02\n" +
	"\x11DetectorRatingReq\x12?\n" +
	"\x06filter\x18\x01 \x01(\v2'.runtime_stats.DetectorRatingReq.FilterR\x06filter\x12&\n" +
	"\x06period\x18\x02 \x01(\v2\x0e.common.PeriodR\x06period\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\"\n" +
	"\x05sorts\x18\x04 \x03(\v2\f.common.SortR\x05sorts\x1ao\n" +
	"\x06Filter\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\"\xb9\x01\n" +
	"\x12DetectorRatingResp\x12E\n" +
	"\bcounters\x18\x01 \x03(\v2).runtime_stats.DetectorRatingResp.CounterR\bcounters\x1a\\\n" +
	"\aCounter\x12\x1f\n" +
	"\vdetector_id\x18\x01 \x01(\tR\n" +
	"detectorId\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count2\x82\x02\n" +
	"\fRuntimeStats\x12q\n" +
	"\vCountEvents\x12&.runtime_stats.RuntimeEventsCounterReq\x1a\x0f.common.Counter\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/stats/runtime-event/count\x12\x7f\n" +
	"\x0eDetectorRating\x12 .runtime_stats.DetectorRatingReq\x1a!.runtime_stats.DetectorRatingResp\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/stats/detector/ratingB'\x92A\x1d\x12\x1b\n" +
	"\x19Runtime History Stats APIZ\x05./apib\x06proto3"

var (
	file_runtime_stats_proto_rawDescOnce sync.Once
	file_runtime_stats_proto_rawDescData []byte
)

func file_runtime_stats_proto_rawDescGZIP() []byte {
	file_runtime_stats_proto_rawDescOnce.Do(func() {
		file_runtime_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_stats_proto_rawDesc), len(file_runtime_stats_proto_rawDesc)))
	})
	return file_runtime_stats_proto_rawDescData
}

var file_runtime_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_runtime_stats_proto_goTypes = []any{
	(*RuntimeEventsCounterReq)(nil),    // 0: runtime_stats.RuntimeEventsCounterReq
	(*DetectorRatingReq)(nil),          // 1: runtime_stats.DetectorRatingReq
	(*DetectorRatingResp)(nil),         // 2: runtime_stats.DetectorRatingResp
	(*DetectorRatingReq_Filter)(nil),   // 3: runtime_stats.DetectorRatingReq.Filter
	(*DetectorRatingResp_Counter)(nil), // 4: runtime_stats.DetectorRatingResp.Counter
	(*Period)(nil),                     // 5: common.Period
	(*Sort)(nil),                       // 6: common.Sort
	(*Counter)(nil),                    // 7: common.Counter
}
var file_runtime_stats_proto_depIdxs = []int32{
	5, // 0: runtime_stats.RuntimeEventsCounterReq.period:type_name -> common.Period
	3, // 1: runtime_stats.DetectorRatingReq.filter:type_name -> runtime_stats.DetectorRatingReq.Filter
	5, // 2: runtime_stats.DetectorRatingReq.period:type_name -> common.Period
	6, // 3: runtime_stats.DetectorRatingReq.sorts:type_name -> common.Sort
	4, // 4: runtime_stats.DetectorRatingResp.counters:type_name -> runtime_stats.DetectorRatingResp.Counter
	0, // 5: runtime_stats.RuntimeStats.CountEvents:input_type -> runtime_stats.RuntimeEventsCounterReq
	1, // 6: runtime_stats.RuntimeStats.DetectorRating:input_type -> runtime_stats.DetectorRatingReq
	7, // 7: runtime_stats.RuntimeStats.CountEvents:output_type -> common.Counter
	2, // 8: runtime_stats.RuntimeStats.DetectorRating:output_type -> runtime_stats.DetectorRatingResp
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_runtime_stats_proto_init() }
func file_runtime_stats_proto_init() {
	if File_runtime_stats_proto != nil {
		return
	}
	file_common_proto_init()
	file_runtime_stats_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_stats_proto_rawDesc), len(file_runtime_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_stats_proto_goTypes,
		DependencyIndexes: file_runtime_stats_proto_depIdxs,
		MessageInfos:      file_runtime_stats_proto_msgTypes,
	}.Build()
	File_runtime_stats_proto = out.File
	file_runtime_stats_proto_goTypes = nil
	file_runtime_stats_proto_depIdxs = nil
}
