apiVersion: v2
appVersion: 3.4.1
dependencies:
- name: common
  repository: file://../common
  version: 0.x.x
description: Prometheus is an open source monitoring and alerting system. It enables
  sysadmins to monitor their infrastructures by collecting metrics from configured
  targets at given intervals.
name: prometheus
version: 0.0.1
