// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: role.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRoleReq) Reset() {
	*x = ReadRoleReq{}
	mi := &file_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRoleReq) ProtoMessage() {}

func (x *ReadRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRoleReq.ProtoReflect.Descriptor instead.
func (*ReadRoleReq) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0}
}

func (x *ReadRoleReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadRoleResp struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	Id              string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName        string                        `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RolePermissions *ReadRoleResp_RolePermissions `protobuf:"bytes,3,opt,name=role_permissions,json=rolePermissions,proto3" json:"role_permissions,omitempty"`
	Description     string                        `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadRoleResp) Reset() {
	*x = ReadRoleResp{}
	mi := &file_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRoleResp) ProtoMessage() {}

func (x *ReadRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRoleResp.ProtoReflect.Descriptor instead.
func (*ReadRoleResp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1}
}

func (x *ReadRoleResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadRoleResp) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ReadRoleResp) GetRolePermissions() *ReadRoleResp_RolePermissions {
	if x != nil {
		return x.RolePermissions
	}
	return nil
}

func (x *ReadRoleResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ReadListRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*ReadRoleResp        `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadListRoleResp) Reset() {
	*x = ReadListRoleResp{}
	mi := &file_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadListRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadListRoleResp) ProtoMessage() {}

func (x *ReadListRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadListRoleResp.ProtoReflect.Descriptor instead.
func (*ReadListRoleResp) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{2}
}

func (x *ReadListRoleResp) GetRoles() []*ReadRoleResp {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ReadRoleResp_Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []string               `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRoleResp_Permission) Reset() {
	*x = ReadRoleResp_Permission{}
	mi := &file_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRoleResp_Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRoleResp_Permission) ProtoMessage() {}

func (x *ReadRoleResp_Permission) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRoleResp_Permission.ProtoReflect.Descriptor instead.
func (*ReadRoleResp_Permission) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ReadRoleResp_Permission) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ReadRoleResp_Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ReadRoleResp_RolePermissions struct {
	state                        protoimpl.MessageState   `protogen:"open.v1"`
	Users                        *ReadRoleResp_Permission `protobuf:"bytes,1,opt,name=users,proto3" json:"users,omitempty"`
	Roles                        *ReadRoleResp_Permission `protobuf:"bytes,2,opt,name=roles,proto3" json:"roles,omitempty"`
	Rules                        *ReadRoleResp_Permission `protobuf:"bytes,3,opt,name=rules,proto3" json:"rules,omitempty"`
	Scanning                     *ReadRoleResp_Permission `protobuf:"bytes,5,opt,name=scanning,proto3" json:"scanning,omitempty"`
	Events                       *ReadRoleResp_Permission `protobuf:"bytes,6,opt,name=events,proto3" json:"events,omitempty"`
	Registries                   *ReadRoleResp_Permission `protobuf:"bytes,7,opt,name=registries,proto3" json:"registries,omitempty"`
	Images                       *ReadRoleResp_Permission `protobuf:"bytes,8,opt,name=images,proto3" json:"images,omitempty"`
	Integrations                 *ReadRoleResp_Permission `protobuf:"bytes,9,opt,name=integrations,proto3" json:"integrations,omitempty"`
	Notifications                *ReadRoleResp_Permission `protobuf:"bytes,10,opt,name=notifications,proto3" json:"notifications,omitempty"`
	SystemSettings               *ReadRoleResp_Permission `protobuf:"bytes,11,opt,name=system_settings,json=systemSettings,proto3" json:"system_settings,omitempty"`
	Clusters                     *ReadRoleResp_Permission `protobuf:"bytes,12,opt,name=clusters,proto3" json:"clusters,omitempty"`
	InvalidatePublicAccessTokens *ReadRoleResp_Permission `protobuf:"bytes,13,opt,name=invalidate_public_access_tokens,json=invalidatePublicAccessTokens,proto3" json:"invalidate_public_access_tokens,omitempty"`
	PublicAccessTokens           *ReadRoleResp_Permission `protobuf:"bytes,14,opt,name=public_access_tokens,json=publicAccessTokens,proto3" json:"public_access_tokens,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ReadRoleResp_RolePermissions) Reset() {
	*x = ReadRoleResp_RolePermissions{}
	mi := &file_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRoleResp_RolePermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRoleResp_RolePermissions) ProtoMessage() {}

func (x *ReadRoleResp_RolePermissions) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRoleResp_RolePermissions.ProtoReflect.Descriptor instead.
func (*ReadRoleResp_RolePermissions) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ReadRoleResp_RolePermissions) GetUsers() *ReadRoleResp_Permission {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetRoles() *ReadRoleResp_Permission {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetRules() *ReadRoleResp_Permission {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetScanning() *ReadRoleResp_Permission {
	if x != nil {
		return x.Scanning
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetEvents() *ReadRoleResp_Permission {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetRegistries() *ReadRoleResp_Permission {
	if x != nil {
		return x.Registries
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetImages() *ReadRoleResp_Permission {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetIntegrations() *ReadRoleResp_Permission {
	if x != nil {
		return x.Integrations
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetNotifications() *ReadRoleResp_Permission {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetSystemSettings() *ReadRoleResp_Permission {
	if x != nil {
		return x.SystemSettings
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetClusters() *ReadRoleResp_Permission {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetInvalidatePublicAccessTokens() *ReadRoleResp_Permission {
	if x != nil {
		return x.InvalidatePublicAccessTokens
	}
	return nil
}

func (x *ReadRoleResp_RolePermissions) GetPublicAccessTokens() *ReadRoleResp_Permission {
	if x != nil {
		return x.PublicAccessTokens
	}
	return nil
}

var File_role_proto protoreflect.FileDescriptor

const file_role_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"role.proto\x12\x04role\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n" +
	"\vReadRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd3\b\n" +
	"\fReadRoleResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12M\n" +
	"\x10role_permissions\x18\x03 \x01(\v2\".role.ReadRoleResp.RolePermissionsR\x0frolePermissions\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x1aH\n" +
	"\n" +
	"Permission\x12\x18\n" +
	"\aactions\x18\x01 \x03(\tR\aactions\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x1a\xda\x06\n" +
	"\x0fRolePermissions\x123\n" +
	"\x05users\x18\x01 \x01(\v2\x1d.role.ReadRoleResp.PermissionR\x05users\x123\n" +
	"\x05roles\x18\x02 \x01(\v2\x1d.role.ReadRoleResp.PermissionR\x05roles\x123\n" +
	"\x05rules\x18\x03 \x01(\v2\x1d.role.ReadRoleResp.PermissionR\x05rules\x129\n" +
	"\bscanning\x18\x05 \x01(\v2\x1d.role.ReadRoleResp.PermissionR\bscanning\x125\n" +
	"\x06events\x18\x06 \x01(\v2\x1d.role.ReadRoleResp.PermissionR\x06events\x12=\n" +
	"\n" +
	"registries\x18\a \x01(\v2\x1d.role.ReadRoleResp.PermissionR\n" +
	"registries\x125\n" +
	"\x06images\x18\b \x01(\v2\x1d.role.ReadRoleResp.PermissionR\x06images\x12A\n" +
	"\fintegrations\x18\t \x01(\v2\x1d.role.ReadRoleResp.PermissionR\fintegrations\x12C\n" +
	"\rnotifications\x18\n" +
	" \x01(\v2\x1d.role.ReadRoleResp.PermissionR\rnotifications\x12F\n" +
	"\x0fsystem_settings\x18\v \x01(\v2\x1d.role.ReadRoleResp.PermissionR\x0esystemSettings\x129\n" +
	"\bclusters\x18\f \x01(\v2\x1d.role.ReadRoleResp.PermissionR\bclusters\x12d\n" +
	"\x1finvalidate_public_access_tokens\x18\r \x01(\v2\x1d.role.ReadRoleResp.PermissionR\x1cinvalidatePublicAccessTokens\x12O\n" +
	"\x14public_access_tokens\x18\x0e \x01(\v2\x1d.role.ReadRoleResp.PermissionR\x12publicAccessTokens\"<\n" +
	"\x10ReadListRoleResp\x12(\n" +
	"\x05roles\x18\x01 \x03(\v2\x12.role.ReadRoleRespR\x05roles2\xac\x01\n" +
	"\x0eRoleController\x12H\n" +
	"\x04Read\x12\x11.role.ReadRoleReq\x1a\x12.role.ReadRoleResp\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/role/{id}\x12P\n" +
	"\bReadList\x12\x16.google.protobuf.Empty\x1a\x16.role.ReadListRoleResp\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/roleB\x16\x92A\f\x12\n" +
	"\n" +
	"\bRole APIZ\x05./apib\x06proto3"

var (
	file_role_proto_rawDescOnce sync.Once
	file_role_proto_rawDescData []byte
)

func file_role_proto_rawDescGZIP() []byte {
	file_role_proto_rawDescOnce.Do(func() {
		file_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_proto_rawDesc), len(file_role_proto_rawDesc)))
	})
	return file_role_proto_rawDescData
}

var file_role_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_role_proto_goTypes = []any{
	(*ReadRoleReq)(nil),                  // 0: role.ReadRoleReq
	(*ReadRoleResp)(nil),                 // 1: role.ReadRoleResp
	(*ReadListRoleResp)(nil),             // 2: role.ReadListRoleResp
	(*ReadRoleResp_Permission)(nil),      // 3: role.ReadRoleResp.Permission
	(*ReadRoleResp_RolePermissions)(nil), // 4: role.ReadRoleResp.RolePermissions
	(*emptypb.Empty)(nil),                // 5: google.protobuf.Empty
}
var file_role_proto_depIdxs = []int32{
	4,  // 0: role.ReadRoleResp.role_permissions:type_name -> role.ReadRoleResp.RolePermissions
	1,  // 1: role.ReadListRoleResp.roles:type_name -> role.ReadRoleResp
	3,  // 2: role.ReadRoleResp.RolePermissions.users:type_name -> role.ReadRoleResp.Permission
	3,  // 3: role.ReadRoleResp.RolePermissions.roles:type_name -> role.ReadRoleResp.Permission
	3,  // 4: role.ReadRoleResp.RolePermissions.rules:type_name -> role.ReadRoleResp.Permission
	3,  // 5: role.ReadRoleResp.RolePermissions.scanning:type_name -> role.ReadRoleResp.Permission
	3,  // 6: role.ReadRoleResp.RolePermissions.events:type_name -> role.ReadRoleResp.Permission
	3,  // 7: role.ReadRoleResp.RolePermissions.registries:type_name -> role.ReadRoleResp.Permission
	3,  // 8: role.ReadRoleResp.RolePermissions.images:type_name -> role.ReadRoleResp.Permission
	3,  // 9: role.ReadRoleResp.RolePermissions.integrations:type_name -> role.ReadRoleResp.Permission
	3,  // 10: role.ReadRoleResp.RolePermissions.notifications:type_name -> role.ReadRoleResp.Permission
	3,  // 11: role.ReadRoleResp.RolePermissions.system_settings:type_name -> role.ReadRoleResp.Permission
	3,  // 12: role.ReadRoleResp.RolePermissions.clusters:type_name -> role.ReadRoleResp.Permission
	3,  // 13: role.ReadRoleResp.RolePermissions.invalidate_public_access_tokens:type_name -> role.ReadRoleResp.Permission
	3,  // 14: role.ReadRoleResp.RolePermissions.public_access_tokens:type_name -> role.ReadRoleResp.Permission
	0,  // 15: role.RoleController.Read:input_type -> role.ReadRoleReq
	5,  // 16: role.RoleController.ReadList:input_type -> google.protobuf.Empty
	1,  // 17: role.RoleController.Read:output_type -> role.ReadRoleResp
	2,  // 18: role.RoleController.ReadList:output_type -> role.ReadListRoleResp
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_role_proto_init() }
func file_role_proto_init() {
	if File_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_proto_rawDesc), len(file_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_proto_goTypes,
		DependencyIndexes: file_role_proto_depIdxs,
		MessageInfos:      file_role_proto_msgTypes,
	}.Build()
	File_role_proto = out.File
	file_role_proto_goTypes = nil
	file_role_proto_depIdxs = nil
}
