// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: user.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	AuthType      string                 `protobuf:"bytes,4,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	RoleId        string                 `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MappingRoleId string                 `protobuf:"bytes,7,opt,name=mapping_role_id,json=mappingRoleId,proto3" json:"mapping_role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CreateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserReq) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserReq) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CreateUserReq) GetMappingRoleId() string {
	if x != nil {
		return x.MappingRoleId
	}
	return ""
}

type UserResp struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username              string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AuthType              string                 `protobuf:"bytes,3,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	LastPasswordChangedAt int64                  `protobuf:"varint,4,opt,name=last_password_changed_at,json=lastPasswordChangedAt,proto3" json:"last_password_changed_at,omitempty"`
	Email                 string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	RoleId                string                 `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MappingRoleId         string                 `protobuf:"bytes,7,opt,name=mapping_role_id,json=mappingRoleId,proto3" json:"mapping_role_id,omitempty"`
	Role                  *ReadRoleResp          `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserResp) Reset() {
	*x = UserResp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResp) ProtoMessage() {}

func (x *UserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResp.ProtoReflect.Descriptor instead.
func (*UserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResp) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *UserResp) GetLastPasswordChangedAt() int64 {
	if x != nil {
		return x.LastPasswordChangedAt
	}
	return 0
}

func (x *UserResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResp) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UserResp) GetMappingRoleId() string {
	if x != nil {
		return x.MappingRoleId
	}
	return ""
}

func (x *UserResp) GetRole() *ReadRoleResp {
	if x != nil {
		return x.Role
	}
	return nil
}

type ReadUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUserReq) Reset() {
	*x = ReadUserReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUserReq) ProtoMessage() {}

func (x *ReadUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUserReq.ProtoReflect.Descriptor instead.
func (*ReadUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ReadUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserResp            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResp) Reset() {
	*x = UserListResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResp) ProtoMessage() {}

func (x *UserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResp.ProtoReflect.Descriptor instead.
func (*UserListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserListResp) GetUsers() []*UserResp {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MappingRoleId string                 `protobuf:"bytes,4,opt,name=mapping_role_id,json=mappingRoleId,proto3" json:"mapping_role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserReq) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UpdateUserReq) GetMappingRoleId() string {
	if x != nil {
		return x.MappingRoleId
	}
	return ""
}

type DeleteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReq) Reset() {
	*x = DeleteUserReq{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReq) ProtoMessage() {}

func (x *DeleteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReq.ProtoReflect.Descriptor instead.
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResp) Reset() {
	*x = DeleteUserResp{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResp) ProtoMessage() {}

func (x *DeleteUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResp.ProtoReflect.Descriptor instead.
func (*DeleteUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ChangePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordReq) Reset() {
	*x = ChangePasswordReq{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReq) ProtoMessage() {}

func (x *ChangePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReq.ProtoReflect.Descriptor instead.
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *ChangePasswordReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangePasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\n" +
	"role.proto\x1a\n" +
	"auth.proto\"\x92\x02\n" +
	"\rCreateUserReq\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1b\n" +
	"\tauth_type\x18\x04 \x01(\tR\bauthType\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12R\n" +
	"\arole_id\x18\x06 \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\x06roleId\x12&\n" +
	"\x0fmapping_role_id\x18\a \x01(\tR\rmappingRoleIdB\x05\n" +
	"\x03_id\"\xbc\x03\n" +
	"\bUserResp\x12I\n" +
	"\x02id\x18\x01 \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tauth_type\x18\x03 \x01(\tR\bauthType\x127\n" +
	"\x18last_password_changed_at\x18\x04 \x01(\x03R\x15lastPasswordChangedAt\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12R\n" +
	"\arole_id\x18\x06 \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\x06roleId\x12a\n" +
	"\x0fmapping_role_id\x18\a \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\rmappingRoleId\x12&\n" +
	"\x04role\x18\b \x01(\v2\x12.role.ReadRoleRespR\x04role\"X\n" +
	"\vReadUserReq\x12I\n" +
	"\x02id\x18\x01 \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\x02id\"4\n" +
	"\fUserListResp\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.user.UserRespR\x05users\"\xa7\x02\n" +
	"\rUpdateUserReq\x12I\n" +
	"\x02id\x18\x01 \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12R\n" +
	"\arole_id\x18\x03 \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\x06roleId\x12a\n" +
	"\x0fmapping_role_id\x18\x04 \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\rmappingRoleId\"Z\n" +
	"\rDeleteUserReq\x12I\n" +
	"\x02id\x18\x01 \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\x02id\"[\n" +
	"\x0eDeleteUserResp\x12I\n" +
	"\x02id\x18\x01 \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\x02id\"z\n" +
	"\x11ChangePasswordReq\x12I\n" +
	"\x02id\x18\x01 \x01(\tB9\x92A62-example: 3fa85f64-5717-4562-b3fc-2c963f66afa6\xa2\x02\x04uuidR\x02id\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2\xed\x03\n" +
	"\x0eUserController\x12F\n" +
	"\x06Create\x12\x13.user.CreateUserReq\x1a\x0e.user.UserResp\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/user\x12D\n" +
	"\x04Read\x12\x11.user.ReadUserReq\x1a\x0e.user.UserResp\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/user/{id}\x12L\n" +
	"\bReadList\x12\x16.google.protobuf.Empty\x1a\x12.user.UserListResp\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/user\x12K\n" +
	"\x06Update\x12\x13.user.UpdateUserReq\x1a\x0e.user.UserResp\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*2\x11/api/v1/user/{id}\x12N\n" +
	"\x06Delete\x12\x13.user.DeleteUserReq\x1a\x14.user.DeleteUserResp\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/user/{id}\x12b\n" +
	"\x0eChangePassword\x12\x17.user.ChangePasswordReq\x1a\x10.auth.SignInResp\"%\x82\xd3\xe4\x93\x02\x1f:\x01*2\x1a/api/v1/user/{id}/passwordB\x16\x92A\f\x12\n" +
	"\n" +
	"\bUser APIZ\x05./apib\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_proto_goTypes = []any{
	(*CreateUserReq)(nil),     // 0: user.CreateUserReq
	(*UserResp)(nil),          // 1: user.UserResp
	(*ReadUserReq)(nil),       // 2: user.ReadUserReq
	(*UserListResp)(nil),      // 3: user.UserListResp
	(*UpdateUserReq)(nil),     // 4: user.UpdateUserReq
	(*DeleteUserReq)(nil),     // 5: user.DeleteUserReq
	(*DeleteUserResp)(nil),    // 6: user.DeleteUserResp
	(*ChangePasswordReq)(nil), // 7: user.ChangePasswordReq
	(*ReadRoleResp)(nil),      // 8: role.ReadRoleResp
	(*emptypb.Empty)(nil),     // 9: google.protobuf.Empty
	(*SignInResp)(nil),        // 10: auth.SignInResp
}
var file_user_proto_depIdxs = []int32{
	8,  // 0: user.UserResp.role:type_name -> role.ReadRoleResp
	1,  // 1: user.UserListResp.users:type_name -> user.UserResp
	0,  // 2: user.UserController.Create:input_type -> user.CreateUserReq
	2,  // 3: user.UserController.Read:input_type -> user.ReadUserReq
	9,  // 4: user.UserController.ReadList:input_type -> google.protobuf.Empty
	4,  // 5: user.UserController.Update:input_type -> user.UpdateUserReq
	5,  // 6: user.UserController.Delete:input_type -> user.DeleteUserReq
	7,  // 7: user.UserController.ChangePassword:input_type -> user.ChangePasswordReq
	1,  // 8: user.UserController.Create:output_type -> user.UserResp
	1,  // 9: user.UserController.Read:output_type -> user.UserResp
	3,  // 10: user.UserController.ReadList:output_type -> user.UserListResp
	1,  // 11: user.UserController.Update:output_type -> user.UserResp
	6,  // 12: user.UserController.Delete:output_type -> user.DeleteUserResp
	10, // 13: user.UserController.ChangePassword:output_type -> auth.SignInResp
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_role_proto_init()
	file_auth_proto_init()
	file_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
