services:
  postgres:
    extends:
      file: ../docker-compose.test.yml
      service: postgres

  test:
    extends:
      file: ../docker-compose.test.yml
      service: test
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - COMPONENT=cluster-manager

networks:
  local:
