version: "3.8"

services:
  reverse-proxy:
    build:
      context: .
    container_name: reverse-proxy
    image: reverse-proxy
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      local:

networks:
  local:
