services:
  postgres:
    extends:
      file: ../docker-compose.test.yml
      service: postgres

  redis:
    extends:
      file: ../docker-compose.test.yml
      service: redis

  test:
    extends:
      file: ../docker-compose.test.yml
      service: test
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - COMPONENT=policy-enforcer

networks:
  local:
