// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: info.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InfoController_GetVersion_FullMethodName      = "/info.InfoController/GetVersion"
	InfoController_GetCentralCSURL_FullMethodName = "/info.InfoController/GetCentralCSURL"
	InfoController_GetGrafanaURL_FullMethodName   = "/info.InfoController/GetGrafanaURL"
)

// InfoControllerClient is the client API for InfoController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InfoControllerClient interface {
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Version, error)
	GetCentralCSURL(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*URL, error)
	GetGrafanaURL(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*URL, error)
}

type infoControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoControllerClient(cc grpc.ClientConnInterface) InfoControllerClient {
	return &infoControllerClient{cc}
}

func (c *infoControllerClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Version, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Version)
	err := c.cc.Invoke(ctx, InfoController_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoControllerClient) GetCentralCSURL(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*URL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(URL)
	err := c.cc.Invoke(ctx, InfoController_GetCentralCSURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoControllerClient) GetGrafanaURL(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*URL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(URL)
	err := c.cc.Invoke(ctx, InfoController_GetGrafanaURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoControllerServer is the server API for InfoController service.
// All implementations must embed UnimplementedInfoControllerServer
// for forward compatibility.
type InfoControllerServer interface {
	GetVersion(context.Context, *emptypb.Empty) (*Version, error)
	GetCentralCSURL(context.Context, *emptypb.Empty) (*URL, error)
	GetGrafanaURL(context.Context, *emptypb.Empty) (*URL, error)
	mustEmbedUnimplementedInfoControllerServer()
}

// UnimplementedInfoControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInfoControllerServer struct{}

func (UnimplementedInfoControllerServer) GetVersion(context.Context, *emptypb.Empty) (*Version, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedInfoControllerServer) GetCentralCSURL(context.Context, *emptypb.Empty) (*URL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCentralCSURL not implemented")
}
func (UnimplementedInfoControllerServer) GetGrafanaURL(context.Context, *emptypb.Empty) (*URL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGrafanaURL not implemented")
}
func (UnimplementedInfoControllerServer) mustEmbedUnimplementedInfoControllerServer() {}
func (UnimplementedInfoControllerServer) testEmbeddedByValue()                        {}

// UnsafeInfoControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfoControllerServer will
// result in compilation errors.
type UnsafeInfoControllerServer interface {
	mustEmbedUnimplementedInfoControllerServer()
}

func RegisterInfoControllerServer(s grpc.ServiceRegistrar, srv InfoControllerServer) {
	// If the following call pancis, it indicates UnimplementedInfoControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InfoController_ServiceDesc, srv)
}

func _InfoController_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoControllerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoController_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoControllerServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoController_GetCentralCSURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoControllerServer).GetCentralCSURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoController_GetCentralCSURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoControllerServer).GetCentralCSURL(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoController_GetGrafanaURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoControllerServer).GetGrafanaURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoController_GetGrafanaURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoControllerServer).GetGrafanaURL(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// InfoController_ServiceDesc is the grpc.ServiceDesc for InfoController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InfoController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "info.InfoController",
	HandlerType: (*InfoControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _InfoController_GetVersion_Handler,
		},
		{
			MethodName: "GetCentralCSURL",
			Handler:    _InfoController_GetCentralCSURL_Handler,
		},
		{
			MethodName: "GetGrafanaURL",
			Handler:    _InfoController_GetGrafanaURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "info.proto",
}
