// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v7.34.1
// source: detector.proto

package api

import (
	context "context"
	tetragon "github.com/runtime-radar/runtime-radar/event-processor/detector/api/tetragon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectResp_Severity int32

const (
	DetectResp_NONE     DetectResp_Severity = 0
	DetectResp_LOW      DetectResp_Severity = 1
	DetectResp_MEDIUM   DetectResp_Severity = 2
	DetectResp_HIGH     DetectResp_Severity = 3
	DetectResp_CRITICAL DetectResp_Severity = 4
)

// Enum value maps for DetectResp_Severity.
var (
	DetectResp_Severity_name = map[int32]string{
		0: "NONE",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	DetectResp_Severity_value = map[string]int32{
		"NONE":     0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x DetectResp_Severity) Enum() *DetectResp_Severity {
	p := new(DetectResp_Severity)
	*p = x
	return p
}

// MitreTactic represents a tactic from Mitre matrix that are covered by a detector.
// Since it's possible for detector to cover only specific techniques, their ids are listed explicitly.
type MitreTactic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Techniques []string `protobuf:"bytes,2,rep,name=techniques,proto3" json:"techniques,omitempty"` // list of techniques' ids
}

func (x *MitreTactic) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *MitreTactic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MitreTactic) GetTechniques() []string {
	if x != nil {
		return x.Techniques
	}
	return nil
}

type InfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InfoReq) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

type InfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version     uint32 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Author      string `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Contact     string `protobuf:"bytes,6,opt,name=contact,proto3" json:"contact,omitempty"`
	License     string `protobuf:"bytes,7,opt,name=license,proto3" json:"license,omitempty"`
	// tactics_covered is an optional list of Mitre tactics that are covered by the detector.
	TacticsCovered []*MitreTactic `protobuf:"bytes,8,rep,name=tactics_covered,json=tacticsCovered,proto3" json:"tactics_covered,omitempty"`
}

func (x *InfoResp) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *InfoResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InfoResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InfoResp) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InfoResp) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *InfoResp) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *InfoResp) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *InfoResp) GetTacticsCovered() []*MitreTactic {
	if x != nil {
		return x.TacticsCovered
	}
	return nil
}

type DetectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *tetragon.GetEventsResponse `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *DetectReq) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DetectReq) GetEvent() *tetragon.GetEventsResponse {
	if x != nil {
		return x.Event
	}
	return nil
}

type DetectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Severity DetectResp_Severity `protobuf:"varint,8,opt,name=severity,proto3,enum=detector.DetectResp_Severity" json:"severity,omitempty"`
	// reason is an optional human-readable message that describes what exactly was detected.
	Reason string `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	// tactics_covered is an optional list of Mitre tactics that are covered via detect.
	TacticsCovered []*MitreTactic `protobuf:"bytes,10,rep,name=tactics_covered,json=tacticsCovered,proto3" json:"tactics_covered,omitempty"`
}

func (x *DetectResp) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DetectResp) GetSeverity() DetectResp_Severity {
	if x != nil {
		return x.Severity
	}
	return DetectResp_NONE
}

func (x *DetectResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DetectResp) GetTacticsCovered() []*MitreTactic {
	if x != nil {
		return x.TacticsCovered
	}
	return nil
}

type TriggerCriteriaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TriggerCriteriaReq) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

type TriggerCriteriaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Criteria links event types with function names. Supported event types are defined in history-api/pkg/model/RuntimeEventType* constants.
	Criteria map[string]*TriggerCriteriaResp_FuncNames `protobuf:"bytes,1,rep,name=criteria,proto3" json:"criteria,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TriggerCriteriaResp) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *TriggerCriteriaResp) GetCriteria() map[string]*TriggerCriteriaResp_FuncNames {
	if x != nil {
		return x.Criteria
	}
	return nil
}

type TriggerCriteriaResp_FuncNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuncNames []string `protobuf:"bytes,1,rep,name=func_names,json=funcNames,proto3" json:"func_names,omitempty"`
}

func (x *TriggerCriteriaResp_FuncNames) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *TriggerCriteriaResp_FuncNames) GetFuncNames() []string {
	if x != nil {
		return x.FuncNames
	}
	return nil
}

// Detector service definition.
// go:plugin type=plugin version=1
type Detector interface {
	Info(context.Context, *InfoReq) (*InfoResp, error)
	Detect(context.Context, *DetectReq) (*DetectResp, error)
	TriggerCriteria(context.Context, *TriggerCriteriaReq) (*TriggerCriteriaResp, error)
}
