syntax = "proto3";
package detector;

import "tetragon/events.proto";

option go_package = "./api";

// Detector service definition.
// go:plugin type=plugin version=1
service Detector {
  rpc Info(InfoReq) returns (InfoResp) {}
  rpc Detect(DetectReq) returns (DetectResp) {}
  rpc TriggerCriteria(TriggerCriteriaReq) returns (TriggerCriteriaResp) {}
}

// MitreTactic represents a tactic from Mitre matrix that are covered by a detector.
// Since it's possible for detector to cover only specific techniques, their ids are listed explicitly.
message MitreTactic {
    string id = 1;
    repeated string techniques = 2; // list of techniques' ids
}

message InfoReq {}

message InfoResp {
  string id = 1;
  string name = 2;
  string description = 3;
  uint32 version = 4;
  string author = 5;
  string contact = 6;
  string license = 7;
  // tactics_covered is an optional list of Mitre tactics that are covered by the detector.
  repeated MitreTactic tactics_covered = 8;
}

message DetectReq {
  tetragon.GetEventsResponse event = 1;
}

message DetectResp {
  enum Severity {
    NONE = 0;
    LOW = 1;
    MEDIUM = 2;
    HIGH = 3;
    CRITICAL = 4;
  }
  Severity severity = 8;
  // reason is an optional human-readable message that describes what exactly was detected.
  string reason = 9;
  // tactics_covered is an optional list of Mitre tactics that are covered via detect.
  repeated MitreTactic tactics_covered = 10;
}

message TriggerCriteriaReq {}

message TriggerCriteriaResp {
  message FuncNames {
    repeated string func_names = 1;
  }
  // Criteria links event types with function names. Supported event types are defined in history-api/pkg/model/RuntimeEventType* constants.
  map<string, FuncNames> criteria = 1;
}
