//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v7.34.1
// source: detector.proto

package api

import (
	context "context"
	wasm "github.com/runtime-radar/go-plugin/wasm"
)

const DetectorPluginAPIVersion = 1

//go:wasmexport detector_api_version
func _detector_api_version() uint64 {
	return DetectorPluginAPIVersion
}

var detector Detector

func RegisterDetector(p Detector) {
	detector = p
}

//go:wasmexport detector_info
func _detector_info(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(InfoReq)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := detector.Info(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport detector_detect
func _detector_detect(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(DetectReq)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := detector.Detect(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport detector_trigger_criteria
func _detector_trigger_criteria(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(TriggerCriteriaReq)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := detector.TriggerCriteria(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
