{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccountName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{- with .Values.global.imagePullSecrets -}}
{{- if (has $.Values.imagePullSecret.name . | ternary $.Values.imagePullSecret.password true) }}
imagePullSecrets:
  {{- range . | uniq }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
