services:
  clickhouse:
    extends:
      file: ../docker-compose.test.yml
      service: clickhouse

  postgres:
    extends:
      file: ../docker-compose.test.yml
      service: postgres

  rabbitmq:
    extends:
      file: ../docker-compose.test.yml
      service: rabbitmq

  test:
    extends:
      file: ../docker-compose.test.yml
      service: test
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - COMPONENT=history-api

networks:
  local:
