// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package database

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
	"github.com/runtime-radar/runtime-radar/kube-manager/pkg/model"
)

// ConfigRepositoryMock implements ConfigRepository
type ConfigRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAdd          func(ctx context.Context, ls ...*model.Config) (err error)
	funcAddOrigin    string
	inspectFuncAdd   func(ctx context.Context, ls ...*model.Config)
	afterAddCounter  uint64
	beforeAddCounter uint64
	AddMock          mConfigRepositoryMockAdd

	funcDelete          func(ctx context.Context, id uuid.UUID) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, id uuid.UUID)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mConfigRepositoryMockDelete

	funcGetLast          func(ctx context.Context, preloadData bool) (cp1 *model.Config, err error)
	funcGetLastOrigin    string
	inspectFuncGetLast   func(ctx context.Context, preloadData bool)
	afterGetLastCounter  uint64
	beforeGetLastCounter uint64
	GetLastMock          mConfigRepositoryMockGetLast
}

// NewConfigRepositoryMock returns a mock for ConfigRepository
func NewConfigRepositoryMock(t minimock.Tester) *ConfigRepositoryMock {
	m := &ConfigRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMock = mConfigRepositoryMockAdd{mock: m}
	m.AddMock.callArgs = []*ConfigRepositoryMockAddParams{}

	m.DeleteMock = mConfigRepositoryMockDelete{mock: m}
	m.DeleteMock.callArgs = []*ConfigRepositoryMockDeleteParams{}

	m.GetLastMock = mConfigRepositoryMockGetLast{mock: m}
	m.GetLastMock.callArgs = []*ConfigRepositoryMockGetLastParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mConfigRepositoryMockAdd struct {
	optional           bool
	mock               *ConfigRepositoryMock
	defaultExpectation *ConfigRepositoryMockAddExpectation
	expectations       []*ConfigRepositoryMockAddExpectation

	callArgs []*ConfigRepositoryMockAddParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ConfigRepositoryMockAddExpectation specifies expectation struct of the ConfigRepository.Add
type ConfigRepositoryMockAddExpectation struct {
	mock               *ConfigRepositoryMock
	params             *ConfigRepositoryMockAddParams
	paramPtrs          *ConfigRepositoryMockAddParamPtrs
	expectationOrigins ConfigRepositoryMockAddExpectationOrigins
	results            *ConfigRepositoryMockAddResults
	returnOrigin       string
	Counter            uint64
}

// ConfigRepositoryMockAddParams contains parameters of the ConfigRepository.Add
type ConfigRepositoryMockAddParams struct {
	ctx context.Context
	ls  []*model.Config
}

// ConfigRepositoryMockAddParamPtrs contains pointers to parameters of the ConfigRepository.Add
type ConfigRepositoryMockAddParamPtrs struct {
	ctx *context.Context
	ls  *[]*model.Config
}

// ConfigRepositoryMockAddResults contains results of the ConfigRepository.Add
type ConfigRepositoryMockAddResults struct {
	err error
}

// ConfigRepositoryMockAddOrigins contains origins of expectations of the ConfigRepository.Add
type ConfigRepositoryMockAddExpectationOrigins struct {
	origin    string
	originCtx string
	originLs  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAdd *mConfigRepositoryMockAdd) Optional() *mConfigRepositoryMockAdd {
	mmAdd.optional = true
	return mmAdd
}

// Expect sets up expected params for ConfigRepository.Add
func (mmAdd *mConfigRepositoryMockAdd) Expect(ctx context.Context, ls ...*model.Config) *mConfigRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("ConfigRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &ConfigRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.paramPtrs != nil {
		mmAdd.mock.t.Fatalf("ConfigRepositoryMock.Add mock is already set by ExpectParams functions")
	}

	mmAdd.defaultExpectation.params = &ConfigRepositoryMockAddParams{ctx, ls}
	mmAdd.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAdd.expectations {
		if minimock.Equal(e.params, mmAdd.defaultExpectation.params) {
			mmAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAdd.defaultExpectation.params)
		}
	}

	return mmAdd
}

// ExpectCtxParam1 sets up expected param ctx for ConfigRepository.Add
func (mmAdd *mConfigRepositoryMockAdd) ExpectCtxParam1(ctx context.Context) *mConfigRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("ConfigRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &ConfigRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.params != nil {
		mmAdd.mock.t.Fatalf("ConfigRepositoryMock.Add mock is already set by Expect")
	}

	if mmAdd.defaultExpectation.paramPtrs == nil {
		mmAdd.defaultExpectation.paramPtrs = &ConfigRepositoryMockAddParamPtrs{}
	}
	mmAdd.defaultExpectation.paramPtrs.ctx = &ctx
	mmAdd.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmAdd
}

// ExpectLsParam2 sets up expected param ls for ConfigRepository.Add
func (mmAdd *mConfigRepositoryMockAdd) ExpectLsParam2(ls ...*model.Config) *mConfigRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("ConfigRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &ConfigRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.params != nil {
		mmAdd.mock.t.Fatalf("ConfigRepositoryMock.Add mock is already set by Expect")
	}

	if mmAdd.defaultExpectation.paramPtrs == nil {
		mmAdd.defaultExpectation.paramPtrs = &ConfigRepositoryMockAddParamPtrs{}
	}
	mmAdd.defaultExpectation.paramPtrs.ls = &ls
	mmAdd.defaultExpectation.expectationOrigins.originLs = minimock.CallerInfo(1)

	return mmAdd
}

// Inspect accepts an inspector function that has same arguments as the ConfigRepository.Add
func (mmAdd *mConfigRepositoryMockAdd) Inspect(f func(ctx context.Context, ls ...*model.Config)) *mConfigRepositoryMockAdd {
	if mmAdd.mock.inspectFuncAdd != nil {
		mmAdd.mock.t.Fatalf("Inspect function is already set for ConfigRepositoryMock.Add")
	}

	mmAdd.mock.inspectFuncAdd = f

	return mmAdd
}

// Return sets up results that will be returned by ConfigRepository.Add
func (mmAdd *mConfigRepositoryMockAdd) Return(err error) *ConfigRepositoryMock {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("ConfigRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &ConfigRepositoryMockAddExpectation{mock: mmAdd.mock}
	}
	mmAdd.defaultExpectation.results = &ConfigRepositoryMockAddResults{err}
	mmAdd.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// Set uses given function f to mock the ConfigRepository.Add method
func (mmAdd *mConfigRepositoryMockAdd) Set(f func(ctx context.Context, ls ...*model.Config) (err error)) *ConfigRepositoryMock {
	if mmAdd.defaultExpectation != nil {
		mmAdd.mock.t.Fatalf("Default expectation is already set for the ConfigRepository.Add method")
	}

	if len(mmAdd.expectations) > 0 {
		mmAdd.mock.t.Fatalf("Some expectations are already set for the ConfigRepository.Add method")
	}

	mmAdd.mock.funcAdd = f
	mmAdd.mock.funcAddOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// When sets expectation for the ConfigRepository.Add which will trigger the result defined by the following
// Then helper
func (mmAdd *mConfigRepositoryMockAdd) When(ctx context.Context, ls ...*model.Config) *ConfigRepositoryMockAddExpectation {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("ConfigRepositoryMock.Add mock is already set by Set")
	}

	expectation := &ConfigRepositoryMockAddExpectation{
		mock:               mmAdd.mock,
		params:             &ConfigRepositoryMockAddParams{ctx, ls},
		expectationOrigins: ConfigRepositoryMockAddExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAdd.expectations = append(mmAdd.expectations, expectation)
	return expectation
}

// Then sets up ConfigRepository.Add return parameters for the expectation previously defined by the When method
func (e *ConfigRepositoryMockAddExpectation) Then(err error) *ConfigRepositoryMock {
	e.results = &ConfigRepositoryMockAddResults{err}
	return e.mock
}

// Times sets number of times ConfigRepository.Add should be invoked
func (mmAdd *mConfigRepositoryMockAdd) Times(n uint64) *mConfigRepositoryMockAdd {
	if n == 0 {
		mmAdd.mock.t.Fatalf("Times of ConfigRepositoryMock.Add mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAdd.expectedInvocations, n)
	mmAdd.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAdd
}

func (mmAdd *mConfigRepositoryMockAdd) invocationsDone() bool {
	if len(mmAdd.expectations) == 0 && mmAdd.defaultExpectation == nil && mmAdd.mock.funcAdd == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAdd.mock.afterAddCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAdd.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Add implements ConfigRepository
func (mmAdd *ConfigRepositoryMock) Add(ctx context.Context, ls ...*model.Config) (err error) {
	mm_atomic.AddUint64(&mmAdd.beforeAddCounter, 1)
	defer mm_atomic.AddUint64(&mmAdd.afterAddCounter, 1)

	mmAdd.t.Helper()

	if mmAdd.inspectFuncAdd != nil {
		mmAdd.inspectFuncAdd(ctx, ls...)
	}

	mm_params := ConfigRepositoryMockAddParams{ctx, ls}

	// Record call args
	mmAdd.AddMock.mutex.Lock()
	mmAdd.AddMock.callArgs = append(mmAdd.AddMock.callArgs, &mm_params)
	mmAdd.AddMock.mutex.Unlock()

	for _, e := range mmAdd.AddMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAdd.AddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAdd.AddMock.defaultExpectation.Counter, 1)
		mm_want := mmAdd.AddMock.defaultExpectation.params
		mm_want_ptrs := mmAdd.AddMock.defaultExpectation.paramPtrs

		mm_got := ConfigRepositoryMockAddParams{ctx, ls}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmAdd.t.Errorf("ConfigRepositoryMock.Add got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAdd.AddMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.ls != nil && !minimock.Equal(*mm_want_ptrs.ls, mm_got.ls) {
				mmAdd.t.Errorf("ConfigRepositoryMock.Add got unexpected parameter ls, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAdd.AddMock.defaultExpectation.expectationOrigins.originLs, *mm_want_ptrs.ls, mm_got.ls, minimock.Diff(*mm_want_ptrs.ls, mm_got.ls))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAdd.t.Errorf("ConfigRepositoryMock.Add got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAdd.AddMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAdd.AddMock.defaultExpectation.results
		if mm_results == nil {
			mmAdd.t.Fatal("No results are set for the ConfigRepositoryMock.Add")
		}
		return (*mm_results).err
	}
	if mmAdd.funcAdd != nil {
		return mmAdd.funcAdd(ctx, ls...)
	}
	mmAdd.t.Fatalf("Unexpected call to ConfigRepositoryMock.Add. %v %v", ctx, ls)
	return
}

// AddAfterCounter returns a count of finished ConfigRepositoryMock.Add invocations
func (mmAdd *ConfigRepositoryMock) AddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.afterAddCounter)
}

// AddBeforeCounter returns a count of ConfigRepositoryMock.Add invocations
func (mmAdd *ConfigRepositoryMock) AddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.beforeAddCounter)
}

// Calls returns a list of arguments used in each call to ConfigRepositoryMock.Add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAdd *mConfigRepositoryMockAdd) Calls() []*ConfigRepositoryMockAddParams {
	mmAdd.mutex.RLock()

	argCopy := make([]*ConfigRepositoryMockAddParams, len(mmAdd.callArgs))
	copy(argCopy, mmAdd.callArgs)

	mmAdd.mutex.RUnlock()

	return argCopy
}

// MinimockAddDone returns true if the count of the Add invocations corresponds
// the number of defined expectations
func (m *ConfigRepositoryMock) MinimockAddDone() bool {
	if m.AddMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddMock.invocationsDone()
}

// MinimockAddInspect logs each unmet expectation
func (m *ConfigRepositoryMock) MinimockAddInspect() {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConfigRepositoryMock.Add at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddCounter := mm_atomic.LoadUint64(&m.afterAddCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && afterAddCounter < 1 {
		if m.AddMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ConfigRepositoryMock.Add at\n%s", m.AddMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ConfigRepositoryMock.Add at\n%s with params: %#v", m.AddMock.defaultExpectation.expectationOrigins.origin, *m.AddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && afterAddCounter < 1 {
		m.t.Errorf("Expected call to ConfigRepositoryMock.Add at\n%s", m.funcAddOrigin)
	}

	if !m.AddMock.invocationsDone() && afterAddCounter > 0 {
		m.t.Errorf("Expected %d calls to ConfigRepositoryMock.Add at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddMock.expectedInvocations), m.AddMock.expectedInvocationsOrigin, afterAddCounter)
	}
}

type mConfigRepositoryMockDelete struct {
	optional           bool
	mock               *ConfigRepositoryMock
	defaultExpectation *ConfigRepositoryMockDeleteExpectation
	expectations       []*ConfigRepositoryMockDeleteExpectation

	callArgs []*ConfigRepositoryMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ConfigRepositoryMockDeleteExpectation specifies expectation struct of the ConfigRepository.Delete
type ConfigRepositoryMockDeleteExpectation struct {
	mock               *ConfigRepositoryMock
	params             *ConfigRepositoryMockDeleteParams
	paramPtrs          *ConfigRepositoryMockDeleteParamPtrs
	expectationOrigins ConfigRepositoryMockDeleteExpectationOrigins
	results            *ConfigRepositoryMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// ConfigRepositoryMockDeleteParams contains parameters of the ConfigRepository.Delete
type ConfigRepositoryMockDeleteParams struct {
	ctx context.Context
	id  uuid.UUID
}

// ConfigRepositoryMockDeleteParamPtrs contains pointers to parameters of the ConfigRepository.Delete
type ConfigRepositoryMockDeleteParamPtrs struct {
	ctx *context.Context
	id  *uuid.UUID
}

// ConfigRepositoryMockDeleteResults contains results of the ConfigRepository.Delete
type ConfigRepositoryMockDeleteResults struct {
	err error
}

// ConfigRepositoryMockDeleteOrigins contains origins of expectations of the ConfigRepository.Delete
type ConfigRepositoryMockDeleteExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mConfigRepositoryMockDelete) Optional() *mConfigRepositoryMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for ConfigRepository.Delete
func (mmDelete *mConfigRepositoryMockDelete) Expect(ctx context.Context, id uuid.UUID) *mConfigRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ConfigRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &ConfigRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("ConfigRepositoryMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &ConfigRepositoryMockDeleteParams{ctx, id}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for ConfigRepository.Delete
func (mmDelete *mConfigRepositoryMockDelete) ExpectCtxParam1(ctx context.Context) *mConfigRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ConfigRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &ConfigRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("ConfigRepositoryMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &ConfigRepositoryMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectIdParam2 sets up expected param id for ConfigRepository.Delete
func (mmDelete *mConfigRepositoryMockDelete) ExpectIdParam2(id uuid.UUID) *mConfigRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ConfigRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &ConfigRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("ConfigRepositoryMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &ConfigRepositoryMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.id = &id
	mmDelete.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the ConfigRepository.Delete
func (mmDelete *mConfigRepositoryMockDelete) Inspect(f func(ctx context.Context, id uuid.UUID)) *mConfigRepositoryMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for ConfigRepositoryMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by ConfigRepository.Delete
func (mmDelete *mConfigRepositoryMockDelete) Return(err error) *ConfigRepositoryMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ConfigRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &ConfigRepositoryMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &ConfigRepositoryMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the ConfigRepository.Delete method
func (mmDelete *mConfigRepositoryMockDelete) Set(f func(ctx context.Context, id uuid.UUID) (err error)) *ConfigRepositoryMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the ConfigRepository.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the ConfigRepository.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the ConfigRepository.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mConfigRepositoryMockDelete) When(ctx context.Context, id uuid.UUID) *ConfigRepositoryMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ConfigRepositoryMock.Delete mock is already set by Set")
	}

	expectation := &ConfigRepositoryMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &ConfigRepositoryMockDeleteParams{ctx, id},
		expectationOrigins: ConfigRepositoryMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up ConfigRepository.Delete return parameters for the expectation previously defined by the When method
func (e *ConfigRepositoryMockDeleteExpectation) Then(err error) *ConfigRepositoryMock {
	e.results = &ConfigRepositoryMockDeleteResults{err}
	return e.mock
}

// Times sets number of times ConfigRepository.Delete should be invoked
func (mmDelete *mConfigRepositoryMockDelete) Times(n uint64) *mConfigRepositoryMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of ConfigRepositoryMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mConfigRepositoryMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements ConfigRepository
func (mmDelete *ConfigRepositoryMock) Delete(ctx context.Context, id uuid.UUID) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, id)
	}

	mm_params := ConfigRepositoryMockDeleteParams{ctx, id}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := ConfigRepositoryMockDeleteParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("ConfigRepositoryMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDelete.t.Errorf("ConfigRepositoryMock.Delete got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("ConfigRepositoryMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the ConfigRepositoryMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, id)
	}
	mmDelete.t.Fatalf("Unexpected call to ConfigRepositoryMock.Delete. %v %v", ctx, id)
	return
}

// DeleteAfterCounter returns a count of finished ConfigRepositoryMock.Delete invocations
func (mmDelete *ConfigRepositoryMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of ConfigRepositoryMock.Delete invocations
func (mmDelete *ConfigRepositoryMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to ConfigRepositoryMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mConfigRepositoryMockDelete) Calls() []*ConfigRepositoryMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*ConfigRepositoryMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *ConfigRepositoryMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *ConfigRepositoryMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConfigRepositoryMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ConfigRepositoryMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ConfigRepositoryMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to ConfigRepositoryMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to ConfigRepositoryMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mConfigRepositoryMockGetLast struct {
	optional           bool
	mock               *ConfigRepositoryMock
	defaultExpectation *ConfigRepositoryMockGetLastExpectation
	expectations       []*ConfigRepositoryMockGetLastExpectation

	callArgs []*ConfigRepositoryMockGetLastParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ConfigRepositoryMockGetLastExpectation specifies expectation struct of the ConfigRepository.GetLast
type ConfigRepositoryMockGetLastExpectation struct {
	mock               *ConfigRepositoryMock
	params             *ConfigRepositoryMockGetLastParams
	paramPtrs          *ConfigRepositoryMockGetLastParamPtrs
	expectationOrigins ConfigRepositoryMockGetLastExpectationOrigins
	results            *ConfigRepositoryMockGetLastResults
	returnOrigin       string
	Counter            uint64
}

// ConfigRepositoryMockGetLastParams contains parameters of the ConfigRepository.GetLast
type ConfigRepositoryMockGetLastParams struct {
	ctx         context.Context
	preloadData bool
}

// ConfigRepositoryMockGetLastParamPtrs contains pointers to parameters of the ConfigRepository.GetLast
type ConfigRepositoryMockGetLastParamPtrs struct {
	ctx         *context.Context
	preloadData *bool
}

// ConfigRepositoryMockGetLastResults contains results of the ConfigRepository.GetLast
type ConfigRepositoryMockGetLastResults struct {
	cp1 *model.Config
	err error
}

// ConfigRepositoryMockGetLastOrigins contains origins of expectations of the ConfigRepository.GetLast
type ConfigRepositoryMockGetLastExpectationOrigins struct {
	origin            string
	originCtx         string
	originPreloadData string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetLast *mConfigRepositoryMockGetLast) Optional() *mConfigRepositoryMockGetLast {
	mmGetLast.optional = true
	return mmGetLast
}

// Expect sets up expected params for ConfigRepository.GetLast
func (mmGetLast *mConfigRepositoryMockGetLast) Expect(ctx context.Context, preloadData bool) *mConfigRepositoryMockGetLast {
	if mmGetLast.mock.funcGetLast != nil {
		mmGetLast.mock.t.Fatalf("ConfigRepositoryMock.GetLast mock is already set by Set")
	}

	if mmGetLast.defaultExpectation == nil {
		mmGetLast.defaultExpectation = &ConfigRepositoryMockGetLastExpectation{}
	}

	if mmGetLast.defaultExpectation.paramPtrs != nil {
		mmGetLast.mock.t.Fatalf("ConfigRepositoryMock.GetLast mock is already set by ExpectParams functions")
	}

	mmGetLast.defaultExpectation.params = &ConfigRepositoryMockGetLastParams{ctx, preloadData}
	mmGetLast.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetLast.expectations {
		if minimock.Equal(e.params, mmGetLast.defaultExpectation.params) {
			mmGetLast.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetLast.defaultExpectation.params)
		}
	}

	return mmGetLast
}

// ExpectCtxParam1 sets up expected param ctx for ConfigRepository.GetLast
func (mmGetLast *mConfigRepositoryMockGetLast) ExpectCtxParam1(ctx context.Context) *mConfigRepositoryMockGetLast {
	if mmGetLast.mock.funcGetLast != nil {
		mmGetLast.mock.t.Fatalf("ConfigRepositoryMock.GetLast mock is already set by Set")
	}

	if mmGetLast.defaultExpectation == nil {
		mmGetLast.defaultExpectation = &ConfigRepositoryMockGetLastExpectation{}
	}

	if mmGetLast.defaultExpectation.params != nil {
		mmGetLast.mock.t.Fatalf("ConfigRepositoryMock.GetLast mock is already set by Expect")
	}

	if mmGetLast.defaultExpectation.paramPtrs == nil {
		mmGetLast.defaultExpectation.paramPtrs = &ConfigRepositoryMockGetLastParamPtrs{}
	}
	mmGetLast.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetLast.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetLast
}

// ExpectPreloadDataParam2 sets up expected param preloadData for ConfigRepository.GetLast
func (mmGetLast *mConfigRepositoryMockGetLast) ExpectPreloadDataParam2(preloadData bool) *mConfigRepositoryMockGetLast {
	if mmGetLast.mock.funcGetLast != nil {
		mmGetLast.mock.t.Fatalf("ConfigRepositoryMock.GetLast mock is already set by Set")
	}

	if mmGetLast.defaultExpectation == nil {
		mmGetLast.defaultExpectation = &ConfigRepositoryMockGetLastExpectation{}
	}

	if mmGetLast.defaultExpectation.params != nil {
		mmGetLast.mock.t.Fatalf("ConfigRepositoryMock.GetLast mock is already set by Expect")
	}

	if mmGetLast.defaultExpectation.paramPtrs == nil {
		mmGetLast.defaultExpectation.paramPtrs = &ConfigRepositoryMockGetLastParamPtrs{}
	}
	mmGetLast.defaultExpectation.paramPtrs.preloadData = &preloadData
	mmGetLast.defaultExpectation.expectationOrigins.originPreloadData = minimock.CallerInfo(1)

	return mmGetLast
}

// Inspect accepts an inspector function that has same arguments as the ConfigRepository.GetLast
func (mmGetLast *mConfigRepositoryMockGetLast) Inspect(f func(ctx context.Context, preloadData bool)) *mConfigRepositoryMockGetLast {
	if mmGetLast.mock.inspectFuncGetLast != nil {
		mmGetLast.mock.t.Fatalf("Inspect function is already set for ConfigRepositoryMock.GetLast")
	}

	mmGetLast.mock.inspectFuncGetLast = f

	return mmGetLast
}

// Return sets up results that will be returned by ConfigRepository.GetLast
func (mmGetLast *mConfigRepositoryMockGetLast) Return(cp1 *model.Config, err error) *ConfigRepositoryMock {
	if mmGetLast.mock.funcGetLast != nil {
		mmGetLast.mock.t.Fatalf("ConfigRepositoryMock.GetLast mock is already set by Set")
	}

	if mmGetLast.defaultExpectation == nil {
		mmGetLast.defaultExpectation = &ConfigRepositoryMockGetLastExpectation{mock: mmGetLast.mock}
	}
	mmGetLast.defaultExpectation.results = &ConfigRepositoryMockGetLastResults{cp1, err}
	mmGetLast.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetLast.mock
}

// Set uses given function f to mock the ConfigRepository.GetLast method
func (mmGetLast *mConfigRepositoryMockGetLast) Set(f func(ctx context.Context, preloadData bool) (cp1 *model.Config, err error)) *ConfigRepositoryMock {
	if mmGetLast.defaultExpectation != nil {
		mmGetLast.mock.t.Fatalf("Default expectation is already set for the ConfigRepository.GetLast method")
	}

	if len(mmGetLast.expectations) > 0 {
		mmGetLast.mock.t.Fatalf("Some expectations are already set for the ConfigRepository.GetLast method")
	}

	mmGetLast.mock.funcGetLast = f
	mmGetLast.mock.funcGetLastOrigin = minimock.CallerInfo(1)
	return mmGetLast.mock
}

// When sets expectation for the ConfigRepository.GetLast which will trigger the result defined by the following
// Then helper
func (mmGetLast *mConfigRepositoryMockGetLast) When(ctx context.Context, preloadData bool) *ConfigRepositoryMockGetLastExpectation {
	if mmGetLast.mock.funcGetLast != nil {
		mmGetLast.mock.t.Fatalf("ConfigRepositoryMock.GetLast mock is already set by Set")
	}

	expectation := &ConfigRepositoryMockGetLastExpectation{
		mock:               mmGetLast.mock,
		params:             &ConfigRepositoryMockGetLastParams{ctx, preloadData},
		expectationOrigins: ConfigRepositoryMockGetLastExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetLast.expectations = append(mmGetLast.expectations, expectation)
	return expectation
}

// Then sets up ConfigRepository.GetLast return parameters for the expectation previously defined by the When method
func (e *ConfigRepositoryMockGetLastExpectation) Then(cp1 *model.Config, err error) *ConfigRepositoryMock {
	e.results = &ConfigRepositoryMockGetLastResults{cp1, err}
	return e.mock
}

// Times sets number of times ConfigRepository.GetLast should be invoked
func (mmGetLast *mConfigRepositoryMockGetLast) Times(n uint64) *mConfigRepositoryMockGetLast {
	if n == 0 {
		mmGetLast.mock.t.Fatalf("Times of ConfigRepositoryMock.GetLast mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetLast.expectedInvocations, n)
	mmGetLast.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetLast
}

func (mmGetLast *mConfigRepositoryMockGetLast) invocationsDone() bool {
	if len(mmGetLast.expectations) == 0 && mmGetLast.defaultExpectation == nil && mmGetLast.mock.funcGetLast == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetLast.mock.afterGetLastCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetLast.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetLast implements ConfigRepository
func (mmGetLast *ConfigRepositoryMock) GetLast(ctx context.Context, preloadData bool) (cp1 *model.Config, err error) {
	mm_atomic.AddUint64(&mmGetLast.beforeGetLastCounter, 1)
	defer mm_atomic.AddUint64(&mmGetLast.afterGetLastCounter, 1)

	mmGetLast.t.Helper()

	if mmGetLast.inspectFuncGetLast != nil {
		mmGetLast.inspectFuncGetLast(ctx, preloadData)
	}

	mm_params := ConfigRepositoryMockGetLastParams{ctx, preloadData}

	// Record call args
	mmGetLast.GetLastMock.mutex.Lock()
	mmGetLast.GetLastMock.callArgs = append(mmGetLast.GetLastMock.callArgs, &mm_params)
	mmGetLast.GetLastMock.mutex.Unlock()

	for _, e := range mmGetLast.GetLastMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmGetLast.GetLastMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetLast.GetLastMock.defaultExpectation.Counter, 1)
		mm_want := mmGetLast.GetLastMock.defaultExpectation.params
		mm_want_ptrs := mmGetLast.GetLastMock.defaultExpectation.paramPtrs

		mm_got := ConfigRepositoryMockGetLastParams{ctx, preloadData}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetLast.t.Errorf("ConfigRepositoryMock.GetLast got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetLast.GetLastMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.preloadData != nil && !minimock.Equal(*mm_want_ptrs.preloadData, mm_got.preloadData) {
				mmGetLast.t.Errorf("ConfigRepositoryMock.GetLast got unexpected parameter preloadData, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetLast.GetLastMock.defaultExpectation.expectationOrigins.originPreloadData, *mm_want_ptrs.preloadData, mm_got.preloadData, minimock.Diff(*mm_want_ptrs.preloadData, mm_got.preloadData))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetLast.t.Errorf("ConfigRepositoryMock.GetLast got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetLast.GetLastMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetLast.GetLastMock.defaultExpectation.results
		if mm_results == nil {
			mmGetLast.t.Fatal("No results are set for the ConfigRepositoryMock.GetLast")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmGetLast.funcGetLast != nil {
		return mmGetLast.funcGetLast(ctx, preloadData)
	}
	mmGetLast.t.Fatalf("Unexpected call to ConfigRepositoryMock.GetLast. %v %v", ctx, preloadData)
	return
}

// GetLastAfterCounter returns a count of finished ConfigRepositoryMock.GetLast invocations
func (mmGetLast *ConfigRepositoryMock) GetLastAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetLast.afterGetLastCounter)
}

// GetLastBeforeCounter returns a count of ConfigRepositoryMock.GetLast invocations
func (mmGetLast *ConfigRepositoryMock) GetLastBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetLast.beforeGetLastCounter)
}

// Calls returns a list of arguments used in each call to ConfigRepositoryMock.GetLast.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetLast *mConfigRepositoryMockGetLast) Calls() []*ConfigRepositoryMockGetLastParams {
	mmGetLast.mutex.RLock()

	argCopy := make([]*ConfigRepositoryMockGetLastParams, len(mmGetLast.callArgs))
	copy(argCopy, mmGetLast.callArgs)

	mmGetLast.mutex.RUnlock()

	return argCopy
}

// MinimockGetLastDone returns true if the count of the GetLast invocations corresponds
// the number of defined expectations
func (m *ConfigRepositoryMock) MinimockGetLastDone() bool {
	if m.GetLastMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetLastMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetLastMock.invocationsDone()
}

// MinimockGetLastInspect logs each unmet expectation
func (m *ConfigRepositoryMock) MinimockGetLastInspect() {
	for _, e := range m.GetLastMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConfigRepositoryMock.GetLast at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetLastCounter := mm_atomic.LoadUint64(&m.afterGetLastCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetLastMock.defaultExpectation != nil && afterGetLastCounter < 1 {
		if m.GetLastMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ConfigRepositoryMock.GetLast at\n%s", m.GetLastMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ConfigRepositoryMock.GetLast at\n%s with params: %#v", m.GetLastMock.defaultExpectation.expectationOrigins.origin, *m.GetLastMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetLast != nil && afterGetLastCounter < 1 {
		m.t.Errorf("Expected call to ConfigRepositoryMock.GetLast at\n%s", m.funcGetLastOrigin)
	}

	if !m.GetLastMock.invocationsDone() && afterGetLastCounter > 0 {
		m.t.Errorf("Expected %d calls to ConfigRepositoryMock.GetLast at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetLastMock.expectedInvocations), m.GetLastMock.expectedInvocationsOrigin, afterGetLastCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ConfigRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddInspect()

			m.MinimockDeleteInspect()

			m.MinimockGetLastInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ConfigRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ConfigRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddDone() &&
		m.MinimockDeleteDone() &&
		m.MinimockGetLastDone()
}
