name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  TASK_VERSION: '3.38.0'
  REGISTRY: ghcr.io
  REPO: runtime-radar
  GO_VERSION: '1.24'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Task
        uses: go-task/setup-task@v1
        with:
          version: ${{ env.TASK_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all Docker images
        run: task docker-build

      - name: Push all Docker images
        env:
          IMAGE_REGISTRY: ${{ env.REGISTRY }}/${{ env.REPO }}
          IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
        run: task docker-push
