name: Test lib

on:
  pull_request:
    paths:
      - lib/**
  push:
    paths:
      - lib/**
    branches:
      - main

env:
  GO_VERSION: '1.24'
  TASK_VERSION: '3.38.0'

jobs:
  test-lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Task
        uses: go-task/setup-task@v1
        with:
          version: ${{ env.TASK_VERSION }}

      - name: Run tests
        working-directory: lib
        run: task test
